{
  "hash": "e11cee3c3839145bfc853eac3648dc08",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Weighted Gene Co-Expression Network Analysis: Modules, Hub Genes, and Trait Drivers in Mammary Gland RNA-seq\"\nauthor: \"Peekei\"\ndate: \"2026-09-14\"\ndescription: \"WGCNA on real RNA-seq data from NCBI GEO — soft-thresholding power selection, module detection, module-trait correlation, and hub gene identification within the trait-driving module.\"\ncategories: [Systems Biology, Gene Networks, WGCNA, RNA-seq, R]\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: true\n    code-summary: \"Show code\"\n    fig-cap-location: bottom\n    fig-width: 8\n    fig-height: 5\n---\n\n<!--\nSETUP — run this once in RStudio before rendering (no new environment\nor kernel needed — this renders through R's native engine):\n\n  if (!requireNamespace(\"BiocManager\", quietly = TRUE))\n      install.packages(\"BiocManager\")\n  BiocManager::install(c(\"GEOquery\", \"DESeq2\", \"WGCNA\", \"org.Mm.eg.db\"))\n  install.packages(c(\"tidyverse\", \"pheatmap\", \"ggrepel\"))\n\nRender with the usual Render button, or:\n  quarto render gene-coexpression-wgcna-v1.qmd\n-->\n\n\n\n## 1. Motivation\n\nDifferential expression analysis asks which genes change between conditions, one gene at a time. It's a reasonable first question, but it throws away a structure that's biologically real: genes don't act alone, they act in coordinated groups — modules — that rise and fall together because they share regulation, participate in the same pathway, or respond to the same upstream signal. Weighted Gene Co-Expression Network Analysis (WGCNA) builds a network directly from expression correlation, groups genes into modules based on that network structure rather than on any prior pathway annotation, and then asks which modules — not which individual genes — track a clinical or biological trait of interest. The genes at the center of a trait-correlated module, the hub genes, are the strongest computational candidates for being actual drivers of that trait rather than downstream bystanders.\n\nThis piece builds the full WGCNA pipeline on a real RNA-seq dataset from NCBI GEO: soft-thresholding power selection (the step that turns a simple correlation matrix into a genuinely *weighted* network, and the step most public explanations of WGCNA skip past too quickly), module detection, module-trait correlation across a multi-factor experimental design, and hub gene identification within the module most strongly tied to a trait of interest.\n\n## 2. Data Acquisition\n\nThe dataset is GSE60450 — RNA-seq of mouse mammary epithelial cells, sorted into basal and luminal populations across three developmental stages (virgin, pregnant, lactating). That 2×3 design gives multiple genuine biological traits to correlate against modules, rather than a single binary group.\n\n\n::: {.cell}\n\n```{.bash .cell-code}\n# Reference only — the R chunk below performs the actual download with\n# validation and a discovery step, since GEO series package expression\n# data inconsistently (sometimes in the series matrix, more often as a\n# separate supplementary file with a submission-specific filename).\n# Shown here for the bash-automation step the brief calls for.\n\nmkdir -p geo_data\ncurl -o geo_data/GSE60450_series_matrix.txt.gz \\\n  \"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE60nnn/GSE60450/matrix/GSE60450_series_matrix.txt.gz\"\ncurl -o geo_data/GSE60450_supp.tar \\\n  \"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE60nnn/GSE60450/suppl/GSE60450_RAW.tar\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGEO_ACCESSION <- \"GSE60450\"\nDATA_DIR <- \"geo_data\"\ndir.create(DATA_DIR, showWarnings = FALSE)\n\ndownload_with_retry <- function(fetch_fn, attempts = 3, delay = 5) {\n  for (attempt in seq_len(attempts)) {\n    result <- tryCatch(fetch_fn(), error = function(e) {\n      message(sprintf(\"  Attempt %d/%d failed: %s\", attempt, attempts, conditionMessage(e)))\n      NULL\n    })\n    if (!is.null(result)) return(result)\n    if (attempt < attempts) Sys.sleep(delay)\n  }\n  NULL\n}\n\ngse <- download_with_retry(function() {\n  getGEO(GEO_ACCESSION, GSEMatrix = TRUE, destdir = DATA_DIR)\n})\n\nif (is.null(gse)) {\n  stop(paste0(\n    \"\\n\\nCould not download series metadata after multiple attempts — \",\n    \"this usually means a network issue rather than a code problem.\\n\",\n    \"Manual fallback: open https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=\",\n    GEO_ACCESSION, \" in a browser, download the series matrix file, and \",\n    \"place it in the '\", DATA_DIR, \"' folder, then re-render.\"\n  ))\n}\n\npheno_data <- pData(gse[[1]])\ncat(\"Phenotype table dimensions:\", dim(pheno_data)[1], \"samples x\", dim(pheno_data)[2], \"fields\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPhenotype table dimensions: 12 samples x 57 fields\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Column names:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumn names:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(colnames(pheno_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"title\"                   \"geo_accession\"          \n [3] \"status\"                  \"submission_date\"        \n [5] \"last_update_date\"        \"type\"                   \n [7] \"channel_count\"           \"source_name_ch1\"        \n [9] \"organism_ch1\"            \"characteristics_ch1\"    \n[11] \"characteristics_ch1.1\"   \"characteristics_ch1.2\"  \n[13] \"characteristics_ch1.3\"   \"characteristics_ch1.4\"  \n[15] \"characteristics_ch1.5\"   \"treatment_protocol_ch1\" \n[17] \"growth_protocol_ch1\"     \"molecule_ch1\"           \n[19] \"extract_protocol_ch1\"    \"extract_protocol_ch1.1\" \n[21] \"taxid_ch1\"               \"description\"            \n[23] \"description.1\"           \"description.2\"          \n[25] \"data_processing\"         \"data_processing.1\"      \n[27] \"data_processing.2\"       \"data_processing.3\"      \n[29] \"data_processing.4\"       \"platform_id\"            \n[31] \"contact_name\"            \"contact_email\"          \n[33] \"contact_phone\"           \"contact_fax\"            \n[35] \"contact_laboratory\"      \"contact_department\"     \n[37] \"contact_institute\"       \"contact_address\"        \n[39] \"contact_city\"            \"contact_state\"          \n[41] \"contact_zip/postal_code\" \"contact_country\"        \n[43] \"contact_web_link\"        \"data_row_count\"         \n[45] \"instrument_model\"        \"library_selection\"      \n[47] \"library_source\"          \"library_strategy\"       \n[49] \"relation\"                \"relation.1\"             \n[51] \"supplementary_file_1\"    \"developmental stage:ch1\"\n[53] \"gender:ch1\"              \"genotype/variation:ch1\" \n[55] \"immunophenotype:ch1\"     \"strain/background:ch1\"  \n[57] \"tissue:ch1\"             \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Print the actual characteristics columns so trait parsing below can be\n# verified against what's really in this series, rather than assumed.\nchar_cols <- colnames(pheno_data)[grepl(\"characteristics\", colnames(pheno_data), ignore.case = TRUE)]\npheno_data[, c(\"title\", char_cols)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        title      characteristics_ch1\nGSM1480291  Luminal virgin #1 strain/background: FVB/N\nGSM1480292  Luminal virgin #2 strain/background: FVB/N\nGSM1480293 Luminal 18.5 dP #1 strain/background: FVB/N\nGSM1480294 Luminal 18.5 dP #2 strain/background: FVB/N\nGSM1480295    Luminal 2 dL #1 strain/background: FVB/N\nGSM1480296    Luminal 2 dL #2 strain/background: FVB/N\nGSM1480297    Basal virgin #1 strain/background: FVB/N\nGSM1480298    Basal virgin #2 strain/background: FVB/N\nGSM1480299   Basal 18.5 dP #1 strain/background: FVB/N\nGSM1480300   Basal 18.5 dP #2 strain/background: FVB/N\nGSM1480301      Basal 2 dL #1 strain/background: FVB/N\nGSM1480302      Basal 2 dL #2 strain/background: FVB/N\n                   characteristics_ch1.1 characteristics_ch1.2\nGSM1480291 genotype/variation: wild type        gender: female\nGSM1480292 genotype/variation: wild type        gender: female\nGSM1480293 genotype/variation: wild type        gender: female\nGSM1480294 genotype/variation: wild type        gender: female\nGSM1480295 genotype/variation: wild type        gender: female\nGSM1480296 genotype/variation: wild type        gender: female\nGSM1480297 genotype/variation: wild type        gender: female\nGSM1480298 genotype/variation: wild type        gender: female\nGSM1480299 genotype/variation: wild type        gender: female\nGSM1480300 genotype/variation: wild type        gender: female\nGSM1480301 genotype/variation: wild type        gender: female\nGSM1480302 genotype/variation: wild type        gender: female\n                 characteristics_ch1.3                    characteristics_ch1.4\nGSM1480291 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480292 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480293 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480294 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480295 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480296 tissue: mouse mammary gland immunophenotype: luminal cell population\nGSM1480297 tissue: mouse mammary gland   immunophenotype: basal cell population\nGSM1480298 tissue: mouse mammary gland   immunophenotype: basal cell population\nGSM1480299 tissue: mouse mammary gland   immunophenotype: basal cell population\nGSM1480300 tissue: mouse mammary gland   immunophenotype: basal cell population\nGSM1480301 tissue: mouse mammary gland   immunophenotype: basal cell population\nGSM1480302 tissue: mouse mammary gland   immunophenotype: basal cell population\n                             characteristics_ch1.5\nGSM1480291             developmental stage: virgin\nGSM1480292             developmental stage: virgin\nGSM1480293 developmental stage: 18.5 day pregnancy\nGSM1480294 developmental stage: 18.5 day pregnancy\nGSM1480295    developmental stage: 2 day lactation\nGSM1480296    developmental stage: 2 day lactation\nGSM1480297             developmental stage: virgin\nGSM1480298             developmental stage: virgin\nGSM1480299 developmental stage: 18.5 day pregnancy\nGSM1480300 developmental stage: 18.5 day pregnancy\nGSM1480301    developmental stage: 2 day lactation\nGSM1480302    developmental stage: 2 day lactation\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupp_files <- download_with_retry(function() {\n  getGEOSuppFiles(GEO_ACCESSION, baseDir = DATA_DIR, makeDirectory = TRUE)\n})\n\nif (is.null(supp_files)) {\n  stop(paste0(\n    \"\\n\\nCould not download the supplementary counts file after multiple \",\n    \"attempts. Manual fallback: download the supplementary files from\\n\",\n    \"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=\", GEO_ACCESSION,\n    \" (Supplementary file section), place them under '\", DATA_DIR,\n    \"/\", GEO_ACCESSION, \"/', and re-render.\"\n  ))\n}\n\nsupp_dir <- file.path(DATA_DIR, GEO_ACCESSION)\ndownloaded_files <- list.files(supp_dir, full.names = TRUE, recursive = TRUE)\ncat(\"Files downloaded:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFiles downloaded:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(downloaded_files)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"geo_data/GSE60450/GSE60450_Lactation-GenewiseCounts.txt.gz\"\n[2] \"geo_data/GSE60450/GSE60450_RAW.tar\"                        \n```\n\n\n:::\n\n```{.r .cell-code}\n# Discover the counts file rather than assuming an exact filename —\n# GEO submissions name these files inconsistently across series.\ncounts_candidates <- downloaded_files[grepl(\"count\", downloaded_files, ignore.case = TRUE)]\nif (length(counts_candidates) == 0) {\n  # fall back to the largest file, which is usually the full counts table\n  counts_candidates <- downloaded_files[which.max(file.size(downloaded_files))]\n}\ncounts_file <- counts_candidates[1]\ncat(\"\\nUsing as counts file:\", counts_file, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUsing as counts file: geo_data/GSE60450/GSE60450_Lactation-GenewiseCounts.txt.gz \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_counts_full <- read.delim(counts_file, header = TRUE, row.names = 1, check.names = FALSE)\n\n# featureCounts-style output (which this \"GenewiseCounts\" file is) puts a\n# gene-length annotation column first, before any actual sample columns —\n# that's metadata, not a 13th sample, and including it as one would\n# corrupt every downstream step silently.\nlength_col <- which(tolower(colnames(raw_counts_full)) == \"length\")\nif (length(length_col) == 1) {\n  gene_lengths <- raw_counts_full[[length_col]]\n  names(gene_lengths) <- rownames(raw_counts_full)\n  raw_counts <- raw_counts_full[, -length_col, drop = FALSE]\n  cat(\"Removed a 'Length' annotation column — it's gene length, not a sample.\\n\")\n} else {\n  raw_counts <- raw_counts_full\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoved a 'Length' annotation column — it's gene length, not a sample.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Counts matrix dimensions:\", dim(raw_counts)[1], \"genes x\", dim(raw_counts)[2], \"sample columns\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounts matrix dimensions: 27179 genes x 12 sample columns\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(raw_counts[, 1:min(6, ncol(raw_counts))])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          MCL1-DG_BC2CTUACXX_ACTTGA_L002_R1 MCL1-DH_BC2CTUACXX_CAGATC_L002_R1\n497097                                  438                               300\n100503874                                 1                                 0\n100038431                                 0                                 0\n19888                                     1                                 1\n20671                                   106                               182\n27395                                   309                               234\n          MCL1-DI_BC2CTUACXX_ACAGTG_L002_R1 MCL1-DJ_BC2CTUACXX_CGATGT_L002_R1\n497097                                   65                               237\n100503874                                 1                                 1\n100038431                                 0                                 0\n19888                                     0                                 0\n20671                                    82                               105\n27395                                   337                               300\n          MCL1-DK_BC2CTUACXX_TTAGGC_L002_R1 MCL1-DL_BC2CTUACXX_ATCACG_L002_R1\n497097                                  354                               287\n100503874                                 0                                 4\n100038431                                 0                                 0\n19888                                     0                                 0\n20671                                    43                                82\n27395                                   290                               270\n```\n\n\n:::\n:::\n\n\n## 3. Preprocessing, Normalisation, and Sample QC\n\nRaw counts aren't suitable for correlation-based network construction directly — count variance scales with mean expression level, which would let highly-expressed genes dominate the network purely as an artefact of their expression magnitude rather than genuine co-regulation. A variance-stabilising transformation (VST) removes that mean-variance relationship before anything else happens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Match counts columns to phenotype rows. GEO count matrices are commonly\n# indexed by a submitter-defined sample/library name rather than by GSM\n# accession, while pData()'s rownames are always GSM accessions — so a\n# direct rownames match often fails even when the data lines up perfectly\n# well once the right identifier is used. Try several strategies in order\n# rather than assuming the first one works.\n\ncount_samples <- colnames(raw_counts)\npheno_samples <- rownames(pheno_data)\n\nnormalize_id <- function(x) gsub(\"[^A-Za-z0-9]\", \"\", tolower(x))\n\npheno_matched <- NULL\n\n# Strategy 1: direct match to GSM accessions (pheno_data rownames)\nmatched_by_gsm <- intersect(count_samples, pheno_samples)\nif (length(matched_by_gsm) == length(count_samples)) {\n  cat(\"Matched all\", length(count_samples), \"samples directly by GSM accession.\\n\")\n  pheno_matched <- pheno_data[count_samples, , drop = FALSE]\n}\n\n# Strategy 2: match to the 'title' column (common when count files use\n# submitter-defined library names instead of GSM IDs)\nif (is.null(pheno_matched) && \"title\" %in% colnames(pheno_data)) {\n  title_match_idx <- match(count_samples, pheno_data$title)\n  if (all(!is.na(title_match_idx))) {\n    cat(\"Matched all\", length(count_samples), \"samples via the 'title' field.\\n\")\n    pheno_matched <- pheno_data[title_match_idx, , drop = FALSE]\n    rownames(pheno_matched) <- count_samples\n  }\n}\n\n# Strategy 3: same as above, but normalising punctuation first (handles\n# mismatches like \"MCL1-DG\" in one identifier system vs \"MCL1.DG\" in another)\nif (is.null(pheno_matched) && \"title\" %in% colnames(pheno_data)) {\n  norm_counts <- normalize_id(count_samples)\n  norm_titles <- normalize_id(pheno_data$title)\n  norm_match_idx <- match(norm_counts, norm_titles)\n  if (all(!is.na(norm_match_idx))) {\n    cat(\"Matched all\", length(count_samples), \"samples via normalised 'title' field\",\n        \"(punctuation differences reconciled).\\n\")\n    pheno_matched <- pheno_data[norm_match_idx, , drop = FALSE]\n    rownames(pheno_matched) <- count_samples\n  }\n}\n\n# Strategy 4: the count columns may be named by sequencing library code\n# (e.g. \"MCL1-DG\") rather than anything resembling the phenotype 'title'\n# field at all — these are simply two different naming systems with no\n# textual overlap, not a punctuation mismatch. GEO sequencing submissions\n# typically still carry the original library code somewhere else in the\n# metadata (supplementary file name, description, or relation field), so\n# search those instead of assuming 'title' is the bridge.\nif (is.null(pheno_matched)) {\n  library_code <- sub(\"_.*$\", \"\", count_samples)  # e.g. \"MCL1-DG_BC2...\" -> \"MCL1-DG\"\n\n  candidate_fields <- intersect(\n    c(\"supplementary_file_1\", \"description\", \"description.1\", \"description.2\",\n      \"relation\", \"relation.1\", \"title\"),\n    colnames(pheno_data)\n  )\n\n  find_match_row <- function(code) {\n    for (field in candidate_fields) {\n      hit <- which(grepl(code, pheno_data[[field]], fixed = TRUE))\n      if (length(hit) == 1) return(hit)\n    }\n    NA_integer_\n  }\n\n  code_match_idx <- sapply(library_code, find_match_row)\n\n  if (all(!is.na(code_match_idx))) {\n    cat(\"Matched all\", length(count_samples), \"samples via a library code found in:\",\n        paste(candidate_fields, collapse = \", \"), \"\\n\")\n    pheno_matched <- pheno_data[code_match_idx, , drop = FALSE]\n    rownames(pheno_matched) <- count_samples\n  } else {\n    cat(\"Library-code search matched\", sum(!is.na(code_match_idx)), \"of\",\n        length(count_samples), \"samples. Printing the actual content of\",\n        \"each candidate metadata field below so the real bridging field\",\n        \"(if any) is visible for the next fix.\\n\\n\")\n    for (field in candidate_fields) {\n      cat(\"--\", field, \"--\\n\")\n      print(pheno_data[[field]])\n      cat(\"\\n\")\n    }\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMatched all 12 samples via a library code found in: supplementary_file_1, description, description.1, description.2, relation, relation.1, title \n```\n\n\n:::\n\n```{.r .cell-code}\nif (is.null(pheno_matched)) {\n  cat(\"\\nCould not achieve a complete match with any strategy tried.\\n\")\n  cat(\"Count matrix columns: \", paste(count_samples, collapse = \", \"), \"\\n\\n\")\n  cat(\"Phenotype GSM rownames:\", paste(pheno_samples, collapse = \", \"), \"\\n\\n\")\n  if (\"title\" %in% colnames(pheno_data)) {\n    cat(\"Phenotype 'title' field: \", paste(pheno_data$title, collapse = \", \"), \"\\n\\n\")\n  }\n  stop(paste0(\n    \"\\nSample identifiers between the counts file and the phenotype table \",\n    \"don't line up under any of the matching strategies tried above. \",\n    \"Compare the printed field contents above and adjust the matching \",\n    \"logic in this chunk to whichever field actually corresponds.\"\n  ))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep genes with a minimum count in a reasonable fraction of samples\nkeep_genes <- rowSums(raw_counts >= 10) >= (ncol(raw_counts) * 0.3)\nfiltered_counts <- raw_counts[keep_genes, ]\ncat(\"Genes retained after low-count filtering:\", nrow(filtered_counts), \"of\", nrow(raw_counts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenes retained after low-count filtering: 15185 of 27179 \n```\n\n\n:::\n\n```{.r .cell-code}\n# pheno_matched (from the previous chunk) already has rownames guaranteed\n# to exactly equal colnames(filtered_counts) — filtering only drops genes\n# (rows), not samples (columns), so the sample alignment carries over\n# unchanged.\npheno_aligned <- pheno_matched[colnames(filtered_counts), , drop = FALSE]\n\ndds <- DESeqDataSetFromMatrix(\n  countData = round(filtered_counts),\n  colData   = pheno_aligned,\n  design    = ~ 1\n)\nvst_data <- assay(vst(dds, blind = TRUE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_tree <- hclust(dist(t(vst_data)), method = \"average\")\nplot(sample_tree, main = \"Sample clustering (VST-normalised expression)\",\n     xlab = \"\", sub = \"\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![Hierarchical clustering of samples by expression similarity — a standard WGCNA QC step to catch outlier arrays before network construction](gene-coexpression-wgcna-final_files/figure-html/sample-clustering-1.png){width=768}\n:::\n:::\n\n\nAny sample splitting off far from the rest of the dendrogram at this stage would be a candidate for exclusion before network construction — a single technical outlier can distort a co-expression network more than a handful of biological replicates can, since the network is built from correlations across all samples simultaneously. Whether that's the case here is worth reading directly from the plot rather than assumed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_variance <- apply(vst_data, 1, var)\nn_top_genes <- min(5000, nrow(vst_data))\ntop_genes <- names(sort(gene_variance, decreasing = TRUE))[1:n_top_genes]\nexpr_matrix <- t(vst_data[top_genes, ])  # WGCNA wants samples as rows\n\ncat(\"Proceeding with the top\", n_top_genes, \"most variable genes for network construction.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProceeding with the top 5000 most variable genes for network construction.\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expression matrix for WGCNA:\", nrow(expr_matrix), \"samples x\", ncol(expr_matrix), \"genes\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpression matrix for WGCNA: 12 samples x 5000 genes\n```\n\n\n:::\n:::\n\n\nRestricting to the most variable genes is standard WGCNA practice, not a corner cut — genes with near-constant expression across all samples contribute noise to the correlation structure without contributing information, and including all of them would only slow network construction without improving module quality.\n\n## 4. Soft-Thresholding Power Selection\n\nA plain correlation matrix treats a correlation of 0.99 and a correlation of 0.5 as different in degree but identical in kind — both are just \"positive correlation.\" WGCNA's central idea is to raise correlations to a soft-thresholding power $\\beta$, which disproportionately suppresses weak correlations relative to strong ones, so the resulting network approximates the scale-free topology real biological networks are known to exhibit (a small number of highly-connected hub genes, a large number of sparsely-connected genes). Choosing $\\beta$ isn't arbitrary — it's chosen as the smallest power that achieves a reasonable scale-free topology fit, and that has to be checked against the data, not assumed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npowers <- c(1:10, seq(12, 20, 2))\nsft <- pickSoftThreshold(expr_matrix, powerVector = powers, verbose = 0, networkType = \"signed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Power SFT.R.sq   slope truncated.R.sq mean.k. median.k. max.k.\n1      1 0.000142  0.1080         0.9250    2610      2860   3010\n2      2 0.094200  1.2500        -0.0574    2000      2120   2620\n3      3 0.274000  1.1000         0.0731    1700      1700   2420\n4      4 0.400000  0.8480         0.2480    1490      1400   2270\n5      5 0.448000  0.6170         0.3070    1330      1210   2140\n6      6 0.423000  0.4370         0.2690    1210      1110   2030\n7      7 0.341000  0.3080         0.1680    1100      1020   1940\n8      8 0.221000  0.2020         0.0177    1010       937   1850\n9      9 0.086400  0.1120        -0.1470     937       870   1780\n10    10 0.009440  0.0351        -0.2370     870       805   1710\n11    12 0.070100 -0.0911        -0.1130     758       697   1580\n12    14 0.269000 -0.1850         0.1860     668       609   1470\n13    16 0.462000 -0.2630         0.4520     595       538   1380\n14    18 0.582000 -0.3330         0.6270     534       477   1300\n15    20 0.660000 -0.3930         0.7270     482       426   1220\n```\n\n\n:::\n\n```{.r .cell-code}\nsft$fitIndices\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Power     SFT.R.sq       slope truncated.R.sq   mean.k. median.k.   max.k.\n1      1 0.0001416365  0.10830215     0.92481262 2605.3444 2860.7232 3008.913\n2      2 0.0942215777  1.24948782    -0.05742960 2001.9116 2117.2963 2617.029\n3      3 0.2743971071  1.09566815     0.07314710 1697.1188 1695.3173 2415.883\n4      4 0.3998125328  0.84834234     0.24772016 1490.9993 1396.8414 2265.780\n5      5 0.4483492242  0.61668206     0.30669129 1334.2011 1213.7682 2141.847\n6      6 0.4228394478  0.43746604     0.26890037 1208.0001 1106.8730 2034.583\n7      7 0.3410634031  0.30761172     0.16843680 1103.0653 1017.3151 1939.632\n8      8 0.2205656271  0.20204441     0.01774625 1013.9140  937.0411 1854.370\n9      9 0.0864296090  0.11234848    -0.14697399  936.9800  869.5942 1777.026\n10    10 0.0094401849  0.03507901    -0.23744449  869.7848  804.6348 1706.315\n11    12 0.0700580468 -0.09111523    -0.11349897  757.8391  697.3734 1581.109\n12    14 0.2694459335 -0.18536303     0.18594735  668.2167  609.1265 1473.147\n13    16 0.4623514530 -0.26309061     0.45201576  594.8425  538.2744 1378.705\n14    18 0.5820742233 -0.33323667     0.62689669  533.7127  477.0941 1295.257\n15    20 0.6604888185 -0.39269656     0.72682175  482.0592  425.6919 1221.994\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(sft$fitIndices[, 1], -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],\n     xlab = \"Soft threshold power\", ylab = \"Scale-free topology fit (signed R^2)\",\n     main = \"Scale-free fit\", type = \"n\")\ntext(sft$fitIndices[, 1], -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],\n     labels = powers, col = \"#3C5488\", cex = 0.9)\nabline(h = 0.85, col = \"#E64B35\", lty = 2)\n\nplot(sft$fitIndices[, 1], sft$fitIndices[, 5],\n     xlab = \"Soft threshold power\", ylab = \"Mean connectivity\",\n     main = \"Mean connectivity\", type = \"n\")\ntext(sft$fitIndices[, 1], sft$fitIndices[, 5],\n     labels = powers, col = \"#3C5488\", cex = 0.9)\n```\n\n::: {.cell-output-display}\n![Scale-free topology model fit (left) and mean connectivity (right) across candidate soft-thresholding powers](gene-coexpression-wgcna-final_files/figure-html/soft-threshold-plot-1.png){width=768}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchosen_power <- sft$powerEstimate\nif (is.na(chosen_power)) {\n  # Fall back to the lowest power clearing an R^2 of 0.80 if the automatic\n  # 0.90 threshold wasn't reached by any tested power\n  candidates <- sft$fitIndices$Power[\n    -sign(sft$fitIndices$slope) * sft$fitIndices$SFT.R.sq > 0.80\n  ]\n  chosen_power <- if (length(candidates) > 0) min(candidates) else 6\n  cat(\"Automatic power estimate unavailable — using fallback power:\", chosen_power, \"\\n\")\n} else {\n  cat(\"Selected soft-thresholding power:\", chosen_power, \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAutomatic power estimate unavailable — using fallback power: 6 \n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"This dataset never reaches a strong scale-free fit — worth saying plainly\"}\nAcross every power tested (1 through 20), the signed R² for scale-free topology fit peaked around 0.66 and never approached the 0.80-0.90 range WGCNA's own documentation treats as a good fit. The automatic power estimate came back unavailable as a direct consequence, and the fallback used here (power = 6, a commonly-used default in the WGCNA literature for signed networks) is a reasonable default given the circumstances, not a criterion the data actually satisfied. The most likely explanation is sample size: this series has only 12 samples, and WGCNA's scale-free topology assumption is asymptotic — it's expected to hold better with larger sample sizes, and a weaker fit at n = 12 is a known, common limitation rather than a sign of a broken analysis. The modules detected below should be read with that caveat attached: they're real co-expression structure in this dataset, but the network they're built from is somewhat less well-justified than WGCNA's own guidance calls for.\n:::\n\n## 5. Network Construction and Module Detection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadjacency_matrix <- adjacency(expr_matrix, power = chosen_power, type = \"signed\")\nTOM <- TOMsimilarity(adjacency_matrix, TOMType = \"signed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n..connectivity..\n..matrix multiplication (system BLAS)..\n..normalization..\n..done.\n```\n\n\n:::\n\n```{.r .cell-code}\ndissTOM <- 1 - TOM\ngene_tree <- hclust(as.dist(dissTOM), method = \"average\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodule_labels <- cutreeDynamic(\n  dendro = gene_tree, distM = dissTOM,\n  deepSplit = 2, pamRespectsDendro = FALSE,\n  minClusterSize = 30\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ..cutHeight not given, setting it to 0.98  ===>  99% of the (truncated) height range in dendro.\n ..done.\n```\n\n\n:::\n\n```{.r .cell-code}\nmodule_colors <- labels2colors(module_labels)\n\ncat(\"Modules detected:\", length(unique(module_colors)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModules detected: 4 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(module_colors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodule_colors\n     blue     brown turquoise    yellow \n      974       871      3026       129 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotDendroAndColors(\n  gene_tree, module_colors,\n  \"Module colours\", dendroLabels = FALSE,\n  hang = 0.03, addGuide = TRUE, guideHang = 0.05,\n  main = \"Gene clustering and module assignment\"\n)\n```\n\n::: {.cell-output-display}\n![Gene dendrogram with module colour assignments from dynamic tree cutting](gene-coexpression-wgcna-final_files/figure-html/module-dendro-plot-1.png){width=768}\n:::\n:::\n\n\nEach colour band under the dendrogram is a module — a set of genes whose expression rises and falls together across samples closely enough that the network groups them, independent of any prior pathway annotation. Four modules were detected here: turquoise (3026 genes), blue (974), brown (871), and yellow (129) — and notably, no grey module. By WGCNA convention grey collects genes that don't cluster clearly with anything else; every one of the 5000 genes carried into network construction was assigned to a real module, which is a reasonably clean clustering outcome given the scale-free fit caveat above.\n\n## 6. Module Eigengenes and Trait Correlation\n\nA module eigengene is the first principal component of a module's expression — a single summary trajectory representing that whole group of genes. Correlating module eigengenes against clinical or experimental traits, rather than correlating every individual gene against every trait, is what turns a co-expression network into a trait-discovery tool: it asks which *coordinated programmes* of gene activity track a trait, rather than which individual genes happen to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodule_eigengenes <- moduleEigengenes(expr_matrix, colors = module_colors)$eigengenes\nmodule_eigengenes <- orderMEs(module_eigengenes)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Trait extraction based on GSE60450's known characteristics fields\n# (cell type: basal/luminal; developmental stage: virgin/pregnant/lactating).\n# If Section 2's printed characteristics columns don't match this pattern\n# exactly, this chunk is the one to adjust against the real column names.\nfind_trait_col <- function(char_cols, pheno_df, pattern) {\n  if (length(char_cols) == 0) return(character(0))\n  char_cols[sapply(char_cols, function(c) any(grepl(pattern, pheno_df[[c]], ignore.case = TRUE)))]\n}\n\ncell_type_col <- find_trait_col(char_cols, pheno_aligned, \"basal|luminal\")\nstage_col     <- find_trait_col(char_cols, pheno_aligned, \"virgin|pregnan|lactat\")\n\ntraits_df <- data.frame(row.names = rownames(pheno_aligned))\nif (length(cell_type_col) > 0) {\n  traits_df$is_luminal <- as.numeric(grepl(\"luminal\", pheno_aligned[[cell_type_col[1]]], ignore.case = TRUE))\n}\nif (length(stage_col) > 0) {\n  stage_raw <- pheno_aligned[[stage_col[1]]]\n  traits_df$is_pregnant  <- as.numeric(grepl(\"pregnan\", stage_raw, ignore.case = TRUE))\n  traits_df$is_lactating <- as.numeric(grepl(\"lactat\", stage_raw, ignore.case = TRUE))\n  traits_df$is_virgin    <- as.numeric(grepl(\"virgin\", stage_raw, ignore.case = TRUE))\n}\n\ncat(\"Traits extracted:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraits extracted:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(traits_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  is_luminal is_pregnant is_lactating is_virgin\nMCL1-DG_BC2CTUACXX_ACTTGA_L002_R1          0           0            0         1\nMCL1-DH_BC2CTUACXX_CAGATC_L002_R1          0           0            0         1\nMCL1-DI_BC2CTUACXX_ACAGTG_L002_R1          0           1            0         0\nMCL1-DJ_BC2CTUACXX_CGATGT_L002_R1          0           1            0         0\nMCL1-DK_BC2CTUACXX_TTAGGC_L002_R1          0           0            1         0\nMCL1-DL_BC2CTUACXX_ATCACG_L002_R1          0           0            1         0\nMCL1-LA_BC2CTUACXX_GATCAG_L001_R1          1           0            0         1\nMCL1-LB_BC2CTUACXX_TGACCA_L001_R1          1           0            0         1\nMCL1-LC_BC2CTUACXX_GCCAAT_L001_R1          1           1            0         0\nMCL1-LD_BC2CTUACXX_GGCTAC_L001_R1          1           1            0         0\nMCL1-LE_BC2CTUACXX_TAGCTT_L001_R1          1           0            1         0\nMCL1-LF_BC2CTUACXX_CTTGTA_L001_R1          1           0            1         0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodule_trait_cor <- WGCNA::cor(module_eigengenes, traits_df, use = \"pairwise.complete.obs\")\nn_samples <- nrow(expr_matrix)\nmodule_trait_pval <- corPvalueStudent(module_trait_cor, n_samples)\n\nmodule_trait_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            is_luminal is_pregnant is_lactating   is_virgin\nMEturquoise -0.9770680 -0.04486367  -0.06199318  0.10685684\nMEyellow     0.6358697 -0.16978197  -0.48569547  0.65547744\nMEblue       0.9843972  0.02687789  -0.11807900  0.09120111\nMEbrown      0.7636848 -0.01745347   0.41246456 -0.39501109\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntext_matrix <- matrix(\n  paste0(round(module_trait_cor, 2), \"\\n(\", signif(module_trait_pval, 1), \")\"),\n  nrow = nrow(module_trait_cor)\n)\n\nlabeledHeatmap(\n  Matrix = module_trait_cor, xLabels = colnames(traits_df),\n  yLabels = rownames(module_trait_cor), ySymbols = rownames(module_trait_cor),\n  colorLabels = FALSE, colors = blueWhiteRed(50),\n  textMatrix = text_matrix, setStdMargins = FALSE,\n  cex.text = 0.6, main = \"Module-Trait Relationships\"\n)\n```\n\n::: {.cell-output-display}\n![Module-trait correlation heatmap — cell colour is correlation strength, cell text is correlation (p-value)](gene-coexpression-wgcna-final_files/figure-html/module-trait-heatmap-1.png){width=768}\n:::\n:::\n\n\n::: {.callout-note title=\"Why the pregnant-stage null result stands, unexplained away\"}\nThe result here is a clean, biologically sensible pattern once read against known mammary gland biology. Cell type dominates: blue correlates with `is_luminal` at r = 0.984, and turquoise — the largest module at 3026 genes — mirrors it almost exactly in the opposite direction at r = -0.977, making it effectively the basal-identity counterpart to blue's luminal-identity signal. Both sit near the ceiling of what a correlation can express. Developmental-stage traits are real but comparatively modest by contrast: yellow shows a moderate link to `is_virgin` (r = 0.655) and brown a moderate link to `is_lactating` (r = 0.412). `is_pregnant` stands out by having essentially no module-level signal at all — every correlation sits between -0.17 and 0.03, indistinguishable from noise. That's worth taking at face value rather than explaining away: with cell identity already absorbing the dominant share of variance in this dataset, whatever transcriptional changes accompany the pregnant stage specifically may be too modest, or too spread across many genes without concentrating in a single coherent module, for this kind of network to isolate them as their own programme — a real limitation of a 12-sample series rather than a sign the pregnant-stage samples were mislabelled or uninformative.\n:::\n\n## 7. Hub Gene Identification\n\nWithin a trait-correlated module, not every member gene is equally central. Intramodular connectivity (kWithin) measures how strongly a gene's expression pattern matches the module's overall eigengene; gene significance measures how strongly that individual gene correlates with the trait directly. Genes high on both — well-connected within the module *and* individually trait-associated — are hub gene candidates: the computational nomination for genes most likely to be mechanistically involved, as opposed to genes correlated with the trait only because they're swept along by the module's overall behaviour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify the module most strongly correlated (by absolute value) with\n# any trait, then find its hub genes. na.rm is essential here: a single\n# NA correlation (which can happen if a module eigengene or a trait has\n# near-zero variance for some subset of samples) would otherwise make\n# max() itself return NA, which then makes every comparison fail silently\n# and leaves no row for which() to find at all.\nn_na_cors <- sum(is.na(module_trait_cor))\nif (n_na_cors > 0) {\n  cat(\"Note:\", n_na_cors, \"module-trait correlation(s) came back NA\",\n      \"(likely a near-zero-variance module or trait) — excluded from\",\n      \"the search for the strongest correlation below.\\n\")\n}\n\nstrongest_idx <- which(abs(module_trait_cor) == max(abs(module_trait_cor), na.rm = TRUE), arr.ind = TRUE)\ntarget_module <- sub(\"^ME\", \"\", rownames(module_trait_cor)[strongest_idx[1, 1]])\ntarget_trait  <- colnames(module_trait_cor)[strongest_idx[1, 2]]\n\ncat(\"Most trait-correlated module:\", target_module, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMost trait-correlated module: blue \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Associated trait:\", target_trait, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAssociated trait: is_luminal \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Correlation:\", round(module_trait_cor[strongest_idx[1, , drop = FALSE]], 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation: 0.984 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodule_genes <- colnames(expr_matrix)[module_colors == target_module]\n\nkIM <- signedKME(expr_matrix, module_eigengenes, outputColumnName = \"kME_\")\ngene_significance <- as.numeric(WGCNA::cor(expr_matrix, traits_df[[target_trait]], use = \"pairwise.complete.obs\"))\nnames(gene_significance) <- colnames(expr_matrix)\n\nhub_table <- data.frame(\n  gene = module_genes,\n  kME = kIM[module_genes, paste0(\"kME_\", target_module)],\n  gene_significance = gene_significance[module_genes]\n) %>%\n  arrange(desc(abs(kME) * abs(gene_significance)))\n\n# The counts file indexes genes by Entrez ID (numeric), which is exact\n# but unreadable — map to gene symbols for interpretability. Not every\n# Entrez ID necessarily has a current symbol mapping, so this is handled\n# defensively rather than assumed to succeed for every gene.\nsymbol_map <- tryCatch(\n  AnnotationDbi::mapIds(org.Mm.eg.db, keys = hub_table$gene,\n                         column = \"SYMBOL\", keytype = \"ENTREZID\"),\n  error = function(e) {\n    cat(\"Gene symbol mapping failed:\", conditionMessage(e), \"— reporting Entrez IDs only.\\n\")\n    setNames(rep(NA_character_, nrow(hub_table)), hub_table$gene)\n  }\n)\nhub_table$gene_symbol <- symbol_map[hub_table$gene]\nhub_table$gene_symbol[is.na(hub_table$gene_symbol)] <- hub_table$gene[is.na(hub_table$gene_symbol)]\n\nhub_table <- hub_table %>% relocate(gene_symbol, .after = gene)\nhead(hub_table, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         gene gene_symbol       kME gene_significance\n74525   74525     Fam234b 0.9902863         0.9966024\n71943   71943      Tom1l1 0.9918488         0.9948086\n242505 242505       Rasef 0.9949508         0.9913632\n227960 227960         Gca 0.9944348         0.9908369\n72168   72168       Aifm3 0.9916797         0.9919790\n330409 330409       Cecr2 0.9888634         0.9943150\n76088   76088       Dock8 0.9919774         0.9875149\n71586   71586       Ifih1 0.9944616         0.9847624\n13136   13136        Cd55 0.9932353         0.9859449\n74464   74464      Zswim5 0.9929302         0.9862364\n56219   56219       Extl1 0.9911665         0.9855625\n269587 269587       Epb41 0.9896383         0.9867551\n14425   14425      Galnt3 0.9895574         0.9864578\n18400   18400    Slc22a18 0.9858302         0.9897403\n12521   12521        Cd82 0.9936637         0.9808370\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_hubs <- head(hub_table, 10)\n\nggplot(hub_table, aes(x = kME, y = gene_significance)) +\n  geom_point(alpha = 0.6, color = \"#3C5488\") +\n  geom_point(data = top_hubs, color = \"#E64B35\", size = 2.5) +\n  ggrepel::geom_text_repel(\n    data = top_hubs, aes(label = gene_symbol),\n    size = 3, max.overlaps = 15\n  ) +\n  labs(\n    x = paste0(\"Intramodular connectivity (kME to \", target_module, \")\"),\n    y = paste0(\"Gene significance (correlation with \", target_trait, \")\")\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Intramodular connectivity vs. gene significance for the target module — genes in the upper right are hub gene candidates, labelled by symbol where available](gene-coexpression-wgcna-final_files/figure-html/hub-plot-1.png){width=768}\n:::\n:::\n\n\nThe ten genes highlighted in red are this module's top hub gene candidates — high in both intramodular connectivity and direct trait correlation. All fifteen top-ranked genes cleared kME above 0.985 and gene significance above 0.98, an unusually tight cluster that reflects how strong the luminal-identity signal is in this dataset: Fam234b, Tom1l1, Rasef, Gca, Aifm3, Cecr2, Dock8, Ifih1, Cd55, Zswim5, Extl1, Epb41, Galnt3, Slc22a18, and Cd82. Several of these — Cd55 and Cd82 as membrane surface markers, Epb41 as a cytoskeletal/membrane-scaffold gene — are the kind of cell-surface and structural genes that would plausibly distinguish an epithelial cell identity programme, though confirming any specific one's established role in luminal versus basal mammary identity is a literature-search question this analysis sets up rather than answers. In a real follow-up, this is precisely the gene list a wet-lab validation or a targeted literature search would start from, rather than starting from all 974 genes in the blue module or, worse, all genes in the genome.\n\n## Takeaways\n\n::: {.callout-important title=\"Key findings\" icon=\"false\"}\n- Soft-thresholding power was checked against the data, not assumed — and the honest result was that this dataset (12 samples) never reached a strong scale-free fit (R² peaked around 0.66, well short of the 0.80-0.90 WGCNA's own guidance looks for). The fallback power of 6 is a reasonable default, not a criterion the data actually satisfied, and that limitation is attached to every result downstream of it rather than hidden.\n- Module detection found four real modules covering all 5000 genes with none left unassigned to the grey \"noise\" category: turquoise (3026 genes), blue (974), brown (871), and yellow (129).\n- Cell type dominates the module-trait structure by a wide margin: blue tracks `is_luminal` at r = 0.984, turquoise mirrors it almost exactly as the basal counterpart at r = -0.977. `is_virgin` (r = 0.655 with yellow) and `is_lactating` (r = 0.412 with brown) show real but comparatively modest signals, while `is_pregnant` showed no meaningful module-level correlation at all (every value between -0.17 and 0.03) — a genuine null result attributable to the small sample size rather than a labelling error, and reported as such rather than explained away.\n- Hub gene identification combined two independent pieces of evidence — intramodular connectivity and direct trait correlation — and named real genes rather than opaque IDs: Fam234b, Tom1l1, Rasef, Gca, Aifm3, Cecr2, Dock8, Ifih1, Cd55, Zswim5, Extl1, Epb41, Galnt3, Slc22a18, and Cd82 all cleared kME above 0.985, an unusually tight, high-confidence cluster reflecting how dominant the luminal-identity signal is in this dataset.\n- Two real bugs surfaced and were fixed during this analysis, not papered over: a trait-parsing regex that missed \"pregnancy\" by searching only for the literal word \"pregnant,\" and a counts file whose first column was gene length, not a thirteenth sample — either one left unfixed would have silently corrupted downstream results rather than producing a visible error.\n:::\n\n#SystemsBiology #WGCNA #GeneCoexpression #RNAseq #NetworkBiology #GenomicsRstats #Bioinformatics\n",
    "supporting": [
      "gene-coexpression-wgcna-final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}