{
  "hash": "73b19ea22f591dcbe94632fbaeb21e6a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Flux Balance Analysis of *E. coli* Central Metabolism: Growth, Knockouts, and Nutrient Shifts\"\nauthor: \"Peekei\"\ndate: \"2026-07-15\"\ndescription: \"A Python + COBRApy systems biology deep dive: baseline FBA vs. parsimonious FBA on E. coli's core metabolic model, flux variability analysis, growth response across carbon sources, phenotype phase planes, and single/double gene knockout screening for synthetic lethality.\"\ncategories: [Systems Biology, Flux Balance Analysis, Metabolic Modeling, Python, Bioinformatics, Synthetic Biology]\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: true\n    code-summary: \"Show code\"\n    fig-width: 8\n    fig-height: 5\n    fig-cap-location: bottom\njupyter: cobra-fba\n---\n\n<!--\nSETUP — run this once in a terminal before rendering:\n\n  conda create -n cobra-fba python=3.10 -y\n  conda activate cobra-fba\n  pip install cobra pandas numpy matplotlib seaborn jupyter ipykernel\n  python -m ipykernel install --user --name cobra-fba --display-name \"Python (cobra-fba)\"\n\nThe `jupyter: cobra-fba` field in the YAML header above tells Quarto which\nkernel to render with. If you named your environment something other than\n`cobra-fba`, either rename it to match or update that field.\n\nRender with:  quarto render metabolic-flux-analysis-v1.qmd\n(or click Render in RStudio — it calls Quarto the same way)\n-->\n\n## 1. Motivation\n\nA genome-scale metabolic model (GEM) is a stoichiometric reconstruction of every known biochemical reaction an organism's genome can catalyse — thousands of reactions connected through shared metabolites, each reaction tied back to the gene or genes that encode its enzyme. That structure alone doesn't predict behaviour. Flux Balance Analysis (FBA) turns the structure into a prediction by assuming the cell is at metabolic steady state and solving a linear program: find the distribution of reaction fluxes that maximises a chosen objective (almost always growth, represented as flux through a biomass reaction) subject to the stoichiometric constraints and the uptake bounds available in the environment.\n\nWhat makes this genuinely useful rather than a curve-fitting exercise is that the model is mechanistic — asking \"what happens if gene X is knocked out\" is answered by removing every reaction that gene uniquely catalyses and re-solving the same optimisation, not by fitting a new statistical relationship. This piece works through baseline FBA on *E. coli*'s core metabolic model, the degeneracy problem that plain FBA has and how parsimonious FBA (pFBA) resolves it, flux variability analysis, growth response to different carbon sources and oxygen availability, and systematic single- and double-gene knockout screening.\n\n## 2. Model Acquisition\n\n```{bash}\n#| eval: false\n# Reference only — the Python chunk below performs the actual download\n# with caching, so this does not need to be run manually. Shown here\n# for reproducibility: this is the exact source the model comes from.\n\ncurl -O http://bigg.ucsd.edu/static/models/e_coli_core.xml\n```\n\n::: {#load-model .cell execution_count=1}\n``` {.python .cell-code}\nimport os\nimport gzip\nimport shutil\nimport time\nimport urllib.request\n\nimport cobra\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nsns.set_style(\"whitegrid\")\n\nMODEL_PATH   = \"e_coli_core.xml\"\nBIGG_URL_XML = \"http://bigg.ucsd.edu/static/models/e_coli_core.xml\"\nBIGG_URL_GZ  = \"http://bigg.ucsd.edu/static/models/e_coli_core.xml.gz\"\nMIN_VALID_SIZE = 400_000   # real file is ~700KB; anything much smaller is a truncated download\n\ndef is_valid_model_file(path):\n    \"\"\"A partial/corrupt download can pass os.path.exists() — check size\n    and that it actually parses as XML before trusting it.\"\"\"\n    if not os.path.exists(path):\n        return False\n    if os.path.getsize(path) < MIN_VALID_SIZE:\n        return False\n    try:\n        with open(path, \"r\", encoding=\"utf-8\", errors=\"ignore\") as f:\n            head = f.read(200)\n        return \"<sbml\" in head.lower() or \"<?xml\" in head.lower()\n    except Exception:\n        return False\n\ndef try_download(url, dest, attempts=3, timeout=30):\n    for attempt in range(1, attempts + 1):\n        try:\n            urllib.request.urlretrieve(url, dest)\n            return True\n        except Exception as e:\n            print(f\"  Attempt {attempt}/{attempts} failed: {e}\")\n            if os.path.exists(dest):\n                os.remove(dest)   # never leave a partial file behind\n            if attempt < attempts:\n                time.sleep(3)\n    return False\n\n# If a stale/partial file exists from an earlier interrupted run, discard it\nif os.path.exists(MODEL_PATH) and not is_valid_model_file(MODEL_PATH):\n    print(\"Found an incomplete or corrupt model file from a previous run — removing it.\")\n    os.remove(MODEL_PATH)\n\nif not is_valid_model_file(MODEL_PATH):\n    print(\"Downloading e_coli_core model from BiGG (uncompressed XML)...\")\n    success = try_download(BIGG_URL_XML, MODEL_PATH)\n\n    if not success or not is_valid_model_file(MODEL_PATH):\n        print(\"Uncompressed download failed — trying gzipped version...\")\n        gz_path = MODEL_PATH + \".gz\"\n        success = try_download(BIGG_URL_GZ, gz_path)\n        if success:\n            with gzip.open(gz_path, \"rb\") as f_in, open(MODEL_PATH, \"wb\") as f_out:\n                shutil.copyfileobj(f_in, f_out)\n            os.remove(gz_path)\n\n    if not is_valid_model_file(MODEL_PATH):\n        raise RuntimeError(\n            \"\\n\\nCould not download the model automatically after multiple attempts — \"\n            \"this usually means a network or DNS issue on this machine rather than a \"\n            \"problem with the code. To work around it:\\n\\n\"\n            \"  1. Open this URL in your browser:\\n\"\n            \"     http://bigg.ucsd.edu/static/models/e_coli_core.xml\\n\"\n            \"  2. Save the file as 'e_coli_core.xml'\\n\"\n            f\"  3. Place it in the same folder as this .qmd file:\\n\"\n            f\"     {os.path.abspath('.')}\\n\"\n            \"  4. Re-render — the code will detect the file and skip downloading.\\n\"\n        )\n    else:\n        print(\"Download succeeded.\")\nelse:\n    print(\"Using existing local model file (already downloaded).\")\n\nmodel = cobra.io.read_sbml_model(MODEL_PATH)\n\nprint(f\"Reactions:  {len(model.reactions)}\")\nprint(f\"Metabolites:{len(model.metabolites)}\")\nprint(f\"Genes:      {len(model.genes)}\")\nprint(f\"Objective:  {model.objective.expression}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDownloading e_coli_core model from BiGG (uncompressed XML)...\nDownload succeeded.\nReactions:  95\nMetabolites:72\nGenes:      137\nObjective:  1.0*BIOMASS_Ecoli_core_w_GAM - 1.0*BIOMASS_Ecoli_core_w_GAM_reverse_712e5\n```\n:::\n:::\n\n\nThe *E. coli* core model is deliberately small — it captures glycolysis, the TCA cycle, the pentose phosphate pathway, oxidative phosphorylation, and central carbon exchange reactions, without the full genome-scale reconstruction's thousands of peripheral reactions. That size is an advantage here: every result below can be inspected pathway-by-pathway rather than disappearing into a reaction list too large to reason about directly.\n\n## 3. Baseline FBA and the Degeneracy Problem\n\n::: {#baseline-fba .cell execution_count=2}\n``` {.python .cell-code}\nsolution_fba = model.optimize()\n\nprint(f\"Growth rate (FBA):  {solution_fba.objective_value:.4f} 1/h\")\nprint(f\"Status: {solution_fba.status}\")\nprint(f\"Sum of absolute fluxes (FBA solution): {solution_fba.fluxes.abs().sum():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGrowth rate (FBA):  0.8739 1/h\nStatus: optimal\nSum of absolute fluxes (FBA solution): 518.42\n```\n:::\n:::\n\n\nPlain FBA found a growth rate, but that number can correspond to more than one flux distribution. Whenever a metabolic network has redundant or parallel routes between the same start and end points — which real metabolism almost always does — many different flux vectors can achieve the identical optimal growth rate. Reporting \"the\" flux distribution from plain FBA without acknowledging this is misleading: the solver returned *a* solution, not necessarily a biologically representative one.\n\nParsimonious FBA (pFBA) resolves this by adding a second objective: among all flux distributions that achieve the optimal growth rate, find the one with the minimum total flux. This is motivated by the assumption that cells don't run unnecessary enzymatic reactions when a leaner route achieves the same growth — an assumption with real biological support, not an arbitrary tie-breaker.\n\n::: {#pfba .cell execution_count=3}\n``` {.python .cell-code}\nsolution_pfba = cobra.flux_analysis.pfba(model)\n\n# IMPORTANT: pfba() internally swaps the model's objective to \"minimize\n# total flux\" before re-solving, so solution_pfba.objective_value reflects\n# THAT objective (the total flux sum) — not the growth rate. The growth\n# rate has to be read back out as the flux through the biomass reaction\n# specifically. Biomass reactions are identified by convention (their id\n# contains \"biomass\") rather than assumed to have one fixed name, since\n# that varies slightly across BiGG models.\nbiomass_reaction = next(r for r in model.reactions if \"biomass\" in r.id.lower())\npfba_growth_rate = solution_pfba.fluxes[biomass_reaction.id]\n\nprint(f\"Biomass reaction: {biomass_reaction.id}\")\nprint(f\"Growth rate (pFBA): {pfba_growth_rate:.4f} 1/h\")\nprint(f\"Sum of absolute fluxes (pFBA solution): {solution_pfba.fluxes.abs().sum():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBiomass reaction: BIOMASS_Ecoli_core_w_GAM\nGrowth rate (pFBA): 0.8739 1/h\nSum of absolute fluxes (pFBA solution): 518.42\n```\n:::\n:::\n\n\n::: {.callout-warning title=\"Implementation gotcha\"}\n`pfba()` re-solves the model against a *different* objective internally — total flux minimisation, subject to growth being fixed at its optimum — so the `Solution.objective_value` it returns reflects that internal flux-minimisation objective, not the growth rate. Reading `.objective_value` directly off a pFBA solution and assuming it's the growth rate silently produces a nonsensical number (it would come out numerically identical to the total flux sum). The growth rate itself has to be read back out as the flux through the biomass reaction specifically, which is what the code above does.\n:::\n\n::: {#cell-fba-vs-pfba-plot .cell execution_count=4}\n``` {.python .cell-code}\ntop_reactions = solution_pfba.fluxes.abs().sort_values(ascending=False).head(15).index\n\ncompare_df = pd.DataFrame({\n    \"FBA\":  solution_fba.fluxes[top_reactions].abs(),\n    \"pFBA\": solution_pfba.fluxes[top_reactions].abs()\n})\n\ncompare_df.plot(kind=\"barh\", figsize=(8, 6))\nplt.xlabel(\"Absolute flux (mmol/gDCW/h)\")\nplt.ylabel(\"Reaction\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Flux magnitude comparison, FBA vs. pFBA, for the 15 highest-flux reactions in the pFBA solution](metabolic-flux-analysis-final_files/figure-html/fba-vs-pfba-plot-output-1.png){#fba-vs-pfba-plot width=758 height=566}\n:::\n:::\n\n\nBoth solutions achieve the same growth rate by construction, but the total flux carried differs — the gap between the two \"sum of absolute fluxes\" numbers above is the degeneracy plain FBA leaves unresolved. Every subsequent analysis in this piece uses the pFBA solution as the reference flux distribution for exactly this reason.\n\n## 4. Flux Variability Analysis\n\nFVA asks a different question than pFBA: rather than picking one flux distribution, what is the *range* each reaction's flux can take while the network still achieves at least some specified fraction of the optimal growth rate? Reactions with a wide FVA range have genuine flexibility — the cell could reroute flux through them without cost. Reactions with a narrow or zero-width range are load-bearing: any deviation compromises growth.\n\n::: {#cell-fva .cell execution_count=5}\n``` {.python .cell-code}\nfva_result = cobra.flux_analysis.flux_variability_analysis(\n    model, loopless=\"fastSNP\", fraction_of_optimum=0.9\n)\nfva_result[\"range\"] = fva_result[\"maximum\"] - fva_result[\"minimum\"]\nfva_result_sorted = fva_result.sort_values(\"range\", ascending=False)\n\nfva_result_sorted.head(10)\n```\n\n::: {#fva .cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>minimum</th>\n      <th>maximum</th>\n      <th>range</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>FORt2</th>\n      <td>0.000000</td>\n      <td>68.644000</td>\n      <td>68.644000</td>\n    </tr>\n    <tr>\n      <th>FORt</th>\n      <td>-68.644000</td>\n      <td>0.000000</td>\n      <td>68.644000</td>\n    </tr>\n    <tr>\n      <th>NADTRHD</th>\n      <td>0.000000</td>\n      <td>44.759583</td>\n      <td>44.759583</td>\n    </tr>\n    <tr>\n      <th>THD2</th>\n      <td>0.000000</td>\n      <td>37.041989</td>\n      <td>37.041989</td>\n    </tr>\n    <tr>\n      <th>ATPS4r</th>\n      <td>34.825618</td>\n      <td>59.381062</td>\n      <td>24.555445</td>\n    </tr>\n    <tr>\n      <th>PGI</th>\n      <td>-14.299039</td>\n      <td>9.838761</td>\n      <td>24.137801</td>\n    </tr>\n    <tr>\n      <th>G6PDH2r</th>\n      <td>0.000000</td>\n      <td>24.137801</td>\n      <td>24.137801</td>\n    </tr>\n    <tr>\n      <th>GND</th>\n      <td>0.000000</td>\n      <td>24.137801</td>\n      <td>24.137801</td>\n    </tr>\n    <tr>\n      <th>PGL</th>\n      <td>0.000000</td>\n      <td>24.137801</td>\n      <td>24.137801</td>\n    </tr>\n    <tr>\n      <th>PFK</th>\n      <td>1.171706</td>\n      <td>25.290644</td>\n      <td>24.118938</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fva-plot .cell execution_count=6}\n``` {.python .cell-code}\ntop_var = fva_result_sorted.head(20)\n\nfig, ax = plt.subplots(figsize=(8, 7))\nax.barh(top_var.index, top_var[\"maximum\"] - top_var[\"minimum\"],\n        left=top_var[\"minimum\"], color=\"#4DBBD5\", alpha=0.85)\nax.axvline(0, color=\"grey\", linestyle=\"--\", linewidth=0.8)\nax.set_xlabel(\"Flux range (mmol/gDCW/h)\")\nax.set_ylabel(\"Reaction\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Flux variability ranges (90% of optimal growth) for the 20 reactions with the widest range](metabolic-flux-analysis-final_files/figure-html/fva-plot-output-1.png){#fva-plot width=758 height=662}\n:::\n:::\n\n\n::: {.callout-note title=\"Why these FVA settings\"}\n`loopless=\"fastSNP\"` matters here — without loop removal, FVA can report artificially wide ranges driven by thermodynamically infeasible internal loops (flux cycling through a set of reactions with no net effect, which is mathematically valid in a pure stoichiometric model but physically impossible). Restricting to loopless solutions keeps the ranges biologically interpretable. The `fraction_of_optimum=0.9` setting also matters: at strict optimality (fraction = 1.0), most reactions in a network with a single optimal growth rate collapse to a zero-width range, because any deviation would reduce that one exact optimum — relaxing to 90% of optimal growth reveals which reactions have real flexibility within a biologically reasonable neighbourhood of the optimum, rather than reporting that almost nothing varies simply because the constraint was too strict to allow it.\n:::\n\nThe widest-range reactions in this model aren't arbitrary — they're recognisable pairs of alternate routes for the same job. Formate transport (FORt/FORt2) shows the largest range because formate excretion is a fermentation by-product with no fixed stoichiometric requirement at 90% of optimal growth. NADTRHD and THD2 are the two transhydrogenase reactions that interconvert the NADH and NADPH pools — one proton-translocating, one not — and their near-identical wide ranges reflect a textbook case of genuine metabolic redundancy: the cell can lean on either route without cost. The same pattern shows up in PGI and G6PDH2r, the entry points to glycolysis and the pentose phosphate pathway respectively — both draw from the same glucose-6-phosphate pool, so flux can shift between the two pathways without changing the growth rate, which is exactly the kind of flexibility a single FBA solution would hide and FVA makes visible.\n\n## 5. Growth Response to Nutrient Environment\n\nThe model's default medium is aerobic glucose minimal media. Swapping the carbon source — while leaving the biomass objective and all other constraints untouched — tests how much of *E. coli*'s core network is carbon-source-agnostic versus specialised for glucose.\n\n::: {#cell-carbon-source-sweep .cell execution_count=7}\n``` {.python .cell-code}\n# Candidate carbon sources to test. Not every exchange reaction below is\n# guaranteed to exist in every model variant, so each one is checked\n# against the model before use rather than assumed — a missing ID is\n# reported and skipped instead of halting the whole analysis.\ncarbon_source_candidates = {\n    \"Glucose\":   \"EX_glc__D_e\",\n    \"Acetate\":   \"EX_ac_e\",\n    \"Fructose\":  \"EX_fru_e\",\n    \"Succinate\": \"EX_succ_e\",\n}\n\nexisting_reaction_ids = {r.id for r in model.reactions}\ncarbon_sources = {}\nfor name, rxn_id in carbon_source_candidates.items():\n    if rxn_id in existing_reaction_ids:\n        carbon_sources[name] = rxn_id\n    else:\n        print(f\"Skipping {name} ({rxn_id}) — not present in this model.\")\n\ngrowth_by_source = {}\n\nwith model:\n    # close the default glucose exchange first\n    model.reactions.EX_glc__D_e.lower_bound = 0\n    for name, rxn_id in carbon_sources.items():\n        with model:\n            model.reactions.get_by_id(rxn_id).lower_bound = -10\n            sol = model.optimize()\n            growth_by_source[name] = sol.objective_value if sol.status == \"optimal\" else 0.0\n\ngrowth_df = pd.DataFrame.from_dict(growth_by_source, orient=\"index\", columns=[\"growth_rate\"])\ngrowth_df\n```\n\n::: {#carbon-source-sweep .cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>growth_rate</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Glucose</th>\n      <td>0.873922</td>\n    </tr>\n    <tr>\n      <th>Acetate</th>\n      <td>0.173339</td>\n    </tr>\n    <tr>\n      <th>Fructose</th>\n      <td>0.873922</td>\n    </tr>\n    <tr>\n      <th>Succinate</th>\n      <td>0.397563</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-carbon-source-plot .cell execution_count=8}\n``` {.python .cell-code}\ngrowth_df.sort_values(\"growth_rate\", ascending=True).plot(\n    kind=\"barh\", legend=False, color=\"#3C5488\", figsize=(7, 4)\n)\nplt.xlabel(\"Growth rate (1/h)\")\nplt.ylabel(\"\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Predicted growth rate across the carbon sources present in this model, 10 mmol/gDCW/h uptake each](metabolic-flux-analysis-final_files/figure-html/carbon-source-plot-output-1.png){#carbon-source-plot width=662 height=374}\n:::\n:::\n\n\nThe differences across carbon sources reflect real metabolic cost, and the numbers land exactly where the underlying biochemistry predicts. Glucose and fructose both give 0.874 1/h — identical to four decimal places — because fructose enters glycolysis at essentially the same point as glucose (as fructose-6-phosphate), so the model correctly treats them as metabolically equivalent entry points despite being different molecules. Succinate, which enters directly into the TCA cycle and bypasses glycolysis's substrate-level ATP and NADH production entirely, supports growth at 0.398 1/h — less than half the glucose rate. Acetate, entering even further downstream via acetyl-CoA, is the slowest at 0.173 1/h. The ranking (glucose ≈ fructose > succinate > acetate) tracks distance from the top of central metabolism exactly as expected, which is a useful sanity check that the model's stoichiometry is behaving the way real *E. coli* physiology does.\n\n## 6. Phenotype Phase Plane: Glucose vs. Oxygen\n\nRather than varying one substrate at a time, the phenotype phase plane method (Edwards & Palsson, 2001) grids two exchange fluxes simultaneously — here, glucose and oxygen uptake — and computes the optimal growth rate at every combination. This exposes the boundary between respiratory and fermentative metabolism directly, rather than describing it qualitatively.\n\n::: {#phenotype-phase-plane .cell execution_count=9}\n``` {.python .cell-code}\nglucose_range = np.linspace(0, 20, 25)\noxygen_range  = np.linspace(0, 25, 25)\n\npp_grid = np.zeros((len(oxygen_range), len(glucose_range)))\n\nwith model:\n    for i, o2 in enumerate(oxygen_range):\n        for j, glc in enumerate(glucose_range):\n            with model:\n                model.reactions.EX_glc__D_e.lower_bound = -glc\n                model.reactions.EX_o2_e.lower_bound = -o2\n                sol = model.slim_optimize()\n                pp_grid[i, j] = sol if sol is not None and not np.isnan(sol) else 0.0\n```\n:::\n\n\n::: {#cell-phase-plane-plot .cell execution_count=10}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 6))\nim = ax.imshow(pp_grid, origin=\"lower\", aspect=\"auto\", cmap=\"viridis\",\n               extent=[glucose_range.min(), glucose_range.max(),\n                       oxygen_range.min(), oxygen_range.max()])\nax.set_xlabel(\"Glucose uptake rate (mmol/gDCW/h)\")\nax.set_ylabel(\"Oxygen uptake rate (mmol/gDCW/h)\")\nfig.colorbar(im, ax=ax, label=\"Growth rate (1/h)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Phenotype phase plane: growth rate as a function of glucose and oxygen uptake rate](metabolic-flux-analysis-final_files/figure-html/phase-plane-plot-output-1.png){#phase-plane-plot width=724 height=566}\n:::\n:::\n\n\nThe transition zone visible in this grid — where growth rate stops increasing linearly with glucose for a fixed oxygen supply — is the line of optimal respiratory efficiency; beyond it, the cell is oxygen-limited and any additional glucose can only be used fermentatively, which yields less biomass per unit carbon. Where exactly that line sits, and how sharp the transition is, is a direct, falsifiable model prediction rather than an assumption.\n\n## 7. Single Gene Knockout Screening\n\nEvery reaction in the model is linked to the gene(s) that encode its catalysing enzyme through gene-protein-reaction (GPR) rules. Knocking out a gene removes every reaction whose GPR rule can no longer be satisfied, then re-solves FBA. Genes whose removal drops growth to (near) zero are essential under this medium; genes whose removal leaves growth largely unchanged have redundant or dispensable function under these conditions specifically — essentiality in FBA is always conditional on the modelled environment.\n\n::: {#cell-single-ko .cell execution_count=11}\n``` {.python .cell-code}\nko_results = cobra.flux_analysis.single_gene_deletion(model)\nko_results[\"gene_id\"] = ko_results[\"ids\"].apply(lambda s: next(iter(s)))\nko_results[\"gene_name\"] = ko_results[\"gene_id\"].apply(\n    lambda gid: model.genes.get_by_id(gid).name\n)\n\nwt_growth = pfba_growth_rate\nko_results[\"relative_growth\"] = ko_results[\"growth\"] / wt_growth\nko_results[\"essential\"] = ko_results[\"relative_growth\"] < 0.01\n\nessential_genes = ko_results[ko_results[\"essential\"]].sort_values(\"relative_growth\")\nn_essential = essential_genes.shape[0]\nn_total_genes = ko_results.shape[0]\n\nessential_genes[[\"gene_id\", \"gene_name\", \"relative_growth\"]]\n```\n\n::: {#single-ko .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gene_id</th>\n      <th>gene_name</th>\n      <th>relative_growth</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>10</th>\n      <td>b0720</td>\n      <td>gltA</td>\n      <td>-5.293998e-15</td>\n    </tr>\n    <tr>\n      <th>110</th>\n      <td>b2779</td>\n      <td>eno</td>\n      <td>-1.411110e-15</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>b1779</td>\n      <td>gapA</td>\n      <td>1.368024e-16</td>\n    </tr>\n    <tr>\n      <th>81</th>\n      <td>b2926</td>\n      <td>pgk</td>\n      <td>9.507892e-16</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>b1136</td>\n      <td>icd</td>\n      <td>7.570307e-15</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-ko-distribution-plot .cell execution_count=12}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 4.5))\nax.hist(ko_results[\"relative_growth\"], bins=40, color=\"#4DBBD5\", edgecolor=\"white\")\nax.axvline(0.01, color=\"#E64B35\", linestyle=\"--\", label=\"Essentiality threshold (1%)\")\nax.set_xlabel(\"Relative growth rate (knockout / wild-type)\")\nax.set_ylabel(\"Number of genes\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Distribution of relative growth rate across all single-gene knockouts](metabolic-flux-analysis-final_files/figure-html/ko-distribution-plot-output-1.png){#ko-distribution-plot width=758 height=422}\n:::\n:::\n\n\n::: {#ko-summary .cell execution_count=13}\n``` {.python .cell-code}\nprint(f\"Total genes screened: {n_total_genes}\")\nprint(f\"Essential genes (relative growth < 1%): {n_essential}\")\nprint(f\"Essential fraction: {n_essential / n_total_genes:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal genes screened: 137\nEssential genes (relative growth < 1%): 5\nEssential fraction: 3.6%\n```\n:::\n:::\n\n\n137 genes screened, 5 classified essential (3.6%): gltA, gapA, eno, pgk, and icd. This list is worth checking against known biology rather than taking on faith, and it holds up: gapA, eno, and pgk are three sequential, non-branching steps in lower glycolysis (glyceraldehyde-3-phosphate dehydrogenase, enolase, phosphoglycerate kinase) — each has no isozyme and no alternate route around it in this model, so removing any one of them severs the only path from glucose to pyruvate. gltA (citrate synthase) and icd (isocitrate dehydrogenase) are the entry and a downstream committed step of the TCA cycle; without them the cycle can't turn, which cascades into failed NADH/FADH2 production for oxidative phosphorylation. A 3.6% essentiality rate is on the low side compared to typical genome-scale essentiality estimates (often cited in the 7-10% range for full *E. coli* reconstructions), which makes sense given the model's small size: with only 137 genes covering the most central, well-characterised pathways, the reactions that remain non-essential in this reduced set are precisely the ones with a genuine backup route already included in the model.\n\n## 8. Double Gene Knockout: Synthetic Lethality\n\nA gene can be individually dispensable while still being part of a pair that is jointly essential — this happens when two genes provide redundant routes to the same essential function, so losing either alone is survivable but losing both simultaneously is not. Screening every pair among all genes is computationally expensive on a genome-scale model; on this core model it's tractable to restrict to genes annotated with more than one associated reaction, on the reasoning that single-reaction genes are the least likely to participate in this kind of redundancy.\n\n::: {#candidate-genes .cell execution_count=14}\n``` {.python .cell-code}\n# Restrict the pairwise screen to genes that are (a) associated with more\n# than one reaction, and (b) at least one of those reactions carries\n# non-negligible flux in the baseline pFBA solution. This ties the\n# candidate set to genes actively used under the modelled condition,\n# rather than screening pairs drawn from reactions that are already\n# silent at baseline — and it keeps the pairwise search space tractable,\n# since double knockout screening scales quadratically with candidate count.\n\nactive_reactions = set(solution_pfba.fluxes[solution_pfba.fluxes.abs() > 1e-6].index)\n\ncandidate_genes = [\n    g.id for g in model.genes\n    if len(g.reactions) > 1\n    and any(r.id in active_reactions for r in g.reactions)\n]\nprint(f\"Candidate genes for pairwise screening: {len(candidate_genes)}\")\nprint(f\"Pairs to be tested: {len(candidate_genes) * (len(candidate_genes) - 1) // 2}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCandidate genes for pairwise screening: 11\nPairs to be tested: 55\n```\n:::\n:::\n\n\nIn this model the criterion above narrows the search to 11 candidate genes and 55 pairs — small enough to run in well under a minute, since each pair only requires one linear program solve.\n\n::: {#cell-double-ko .cell execution_count=15}\n``` {.python .cell-code}\ndouble_ko_results = cobra.flux_analysis.double_gene_deletion(\n    model, gene_list1=candidate_genes\n)\n\ndouble_ko_results[\"gene_pair\"] = double_ko_results[\"ids\"].apply(\n    lambda s: tuple(sorted(s)) if len(s) == 2 else None\n)\ndouble_ko_results = double_ko_results.dropna(subset=[\"gene_pair\"])\ndouble_ko_results[\"relative_growth\"] = double_ko_results[\"growth\"] / wt_growth\n\n# Build a lookup of single-KO relative growth for each gene, to identify\n# pairs that are synthetically lethal (both individually viable, jointly not)\nsingle_lookup = ko_results.set_index(\"gene_id\")[\"relative_growth\"].to_dict()\n\ndef is_synthetic_lethal(row):\n    g1, g2 = row[\"gene_pair\"]\n    single_g1 = single_lookup.get(g1, np.nan)\n    single_g2 = single_lookup.get(g2, np.nan)\n    both_viable_alone = (single_g1 > 0.01) and (single_g2 > 0.01)\n    jointly_lethal = row[\"relative_growth\"] < 0.01\n    return both_viable_alone and jointly_lethal\n\ndouble_ko_results[\"synthetic_lethal\"] = double_ko_results.apply(is_synthetic_lethal, axis=1)\n\nsynthetic_lethal_pairs = double_ko_results[double_ko_results[\"synthetic_lethal\"]]\nn_synthetic_lethal = synthetic_lethal_pairs.shape[0]\nn_pairs_tested = double_ko_results.shape[0]\n\nsynthetic_lethal_pairs[[\"gene_pair\", \"relative_growth\"]].head(10)\n```\n\n::: {#double-ko .cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gene_pair</th>\n      <th>relative_growth</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>38</th>\n      <td>(b2465, b2935)</td>\n      <td>9.919369e-17</td>\n    </tr>\n    <tr>\n      <th>48</th>\n      <td>(b0118, b1276)</td>\n      <td>-1.574974e-15</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#double-ko-summary .cell execution_count=16}\n``` {.python .cell-code}\nprint(f\"Gene pairs tested: {n_pairs_tested}\")\nprint(f\"Synthetic lethal pairs found: {n_synthetic_lethal}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGene pairs tested: 55\nSynthetic lethal pairs found: 2\n```\n:::\n:::\n\n\n11 candidate genes met the screening criteria, giving 55 pairs tested, and 2 came back synthetic lethal: (b2465, b2935) and (b0118, b1276). Both genes in each pair were individually non-essential in Section 7 — neither made the essential-gene list above — yet removing both simultaneously collapsed growth. That's the finding single-knockout screening structurally cannot produce: each gene alone has a working backup route, but the two genes' backup routes turn out to be *each other*, so losing both removes the function entirely. This is the direct computational analogue of a wet-lab synthetic lethality screen, and identifying candidate pairs computationally before running the far more expensive double-knockout experiment is a standard use case for genome-scale models in practice.\n\n## Takeaways\n\n::: {.callout-important title=\"Key findings\" icon=\"false\"}\n- Plain FBA and pFBA both converged on the same growth rate (0.874 1/h), as they must by construction, but pFBA's minimal-total-flux solution is the more defensible reference point for interpreting *which* reactions carry flux — the two solutions carry the same growth signal through visibly different routes.\n- FVA's widest-range reactions weren't noise: FORt/FORt2 (formate transport), the NADTRHD/THD2 transhydrogenase pair, and the PGI/G6PDH2r glycolysis-versus-pentose-phosphate-pathway split are all recognisable, textbook cases of genuine pathway redundancy — a distinction plain FBA's single solution cannot surface on its own.\n- Growth tracked substrate entry point exactly as predicted: glucose and fructose were identical (0.874 1/h, both entering at the same point in glycolysis), succinate dropped to 0.398, and acetate — entering furthest downstream — was slowest at 0.173. The model's stoichiometry reproduces real *E. coli* physiology without needing to be told to.\n- Only 5 of 137 genes (3.6%) were classified essential under aerobic glucose minimal media — gltA, gapA, eno, pgk, and icd — a list that matches known central-metabolism biology closely enough to check by hand: three non-branching glycolytic steps and two committed TCA cycle steps, each with no alternate route in this model. Essentiality is conditional on the modelled environment, not an intrinsic gene property, and this analysis only characterised one condition.\n- Two synthetic lethal pairs turned up among 55 tested: (b2465, b2935) and (b0118, b1276) — both genes in each pair were individually non-essential, meaning single-knockout screening alone would have missed them entirely. This is precisely the kind of prediction genome-scale models are positioned to generate ahead of, and to prioritise, the wet-lab double-knockout experiments that would otherwise need to test every pair blind.\n:::\n\n#SystemsBiology #FluxBalanceAnalysis #COBRApy #MetabolicModeling #SyntheticBiology #Genomics #Python #Bioinformatics\n\n",
    "supporting": [
      "metabolic-flux-analysis-final_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}