{
  "hash": "0ad9877e324f9fff2825f6536f92c17a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Dynamic Modeling of a Three-Tier Kinase Cascade: Ultrasensitivity and Drug Target Identification\"\nauthor: \"Peekei\"\ndate: \"2026-09-14\"\ndescription: \"ODE modeling of a MAPK-style kinase cascade in SciPy — dose-response ultrasensitivity, the zero-order kinetic regime, and parameter sensitivity analysis for drug target ranking.\"\ncategories: [Systems Biology, Signal Transduction, ODE Modeling, Python, Computational Biology]\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: true\n    code-summary: \"Show code\"\n    fig-cap-location: bottom\n    fig-width: 8\n    fig-height: 5\njupyter: signaling-ode\n---\n\n<!--\nSETUP — run this once in a terminal before rendering:\n\n  conda create -n signaling-ode python=3.10 -y\n  conda activate signaling-ode\n  pip install scipy numpy pandas matplotlib seaborn jupyter ipykernel\n  python -m ipykernel install --user --name signaling-ode --display-name \"Python (signaling-ode)\"\n\nThe `jupyter: signaling-ode` field in the YAML header above tells Quarto\nwhich kernel to render with. If you named your environment something\nother than `signaling-ode`, either rename it to match or update that field.\n\nRender with:  quarto render signaling-pathway-ode-v1.qmd\n(or click Render in RStudio — it calls Quarto the same way)\n-->\n\n## 1. Motivation\n\nA cell receiving an external signal — a growth factor binding its receptor, a hormone, a stress cue — rarely responds to that signal in direct proportion to its strength. Instead, many signal transduction pathways behave more like switches: below some threshold, almost nothing happens; above it, the pathway commits fully. The three-tier kinase cascade at the heart of the MAPK pathway (Raf → MEK → ERK, and its analogues across essentially every eukaryotic signaling system) is the canonical example of how this switch-like behaviour emerges — not from any single ultrasensitive component, but from cascading several only-mildly-sensitive enzymatic steps in series.\n\nThis piece builds that cascade as a system of ordinary differential equations, characterises the ultrasensitivity that emerges as the signal propagates from tier to tier, checks explicitly whether the model is actually operating in the kinetic regime that produces switch-like behaviour (it is possible to build the same cascade topology and get a graded, non-switch-like response — the regime matters, and asserting ultrasensitivity without checking it is a common shortcut), and finishes with a parameter sensitivity analysis to identify which kinetic step the pathway's output depends on most — the computational equivalent of asking which enzyme, if drugged, would shut the pathway down hardest.\n\n## 2. Model Construction\n\nEach tier of the cascade is a kinase that exists in an inactive and an active (phosphorylated) form. The previous tier's active kinase catalyses phosphorylation of the next tier; a constitutively active phosphatase catalyses the reverse reaction. Both reactions are modelled with saturable (Michaelis-Menten-style) kinetics — the Goldbeter-Koshland formulation that underlies essentially every published kinase cascade model of this kind:\n\n$$\\frac{d[E_i^P]}{dt} = \\frac{V_{on,i} \\cdot (E_{i,tot} - E_i^P)}{K_{on,i} + (E_{i,tot} - E_i^P)} - \\frac{V_{off,i} \\cdot E_i^P}{K_{off,i} + E_i^P}$$\n\nwhere $V_{on,1}$ is driven by the external signal $S(t)$, and $V_{on,2}$, $V_{on,3}$ are driven by the active fraction of the tier immediately upstream — this upstream-driving-downstream structure is what makes it a cascade rather than three independent switches.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy.integrate import solve_ivp\nfrom scipy.optimize import curve_fit\n\nsns.set_style(\"whitegrid\")\n\n# Total protein concentration at each tier (normalised units)\nE_total = np.array([1.0, 1.0, 1.0])\n\n# Catalytic rate constants for the forward (activating) reaction at each tier\nk_cat = np.array([1.0, 1.0, 1.0])\n\n# Michaelis constants for the forward reaction — small relative to E_total\n# puts the system in the \"zero-order\" ultrasensitive regime (Section 6\n# checks this explicitly rather than assuming it)\nKm_on = np.array([0.05, 0.05, 0.05])\n\n# Michaelis constants for the reverse (phosphatase) reaction\nKm_off = np.array([0.05, 0.05, 0.05])\n\n# Phosphatase Vmax at each tier — constitutive, signal-independent\nVmax_off = np.array([0.5, 0.5, 0.5])\n\n\ndef cascade_ode(t, y, S_func, k_cat, Km_on, Km_off, Vmax_off, E_total):\n    E1_P, E2_P, E3_P = y\n    S = S_func(t)\n\n    E1, E2, E3 = E_total - np.array([E1_P, E2_P, E3_P])\n\n    v1_on  = k_cat[0] * S    * E1 / (Km_on[0] + E1)\n    v2_on  = k_cat[1] * E1_P * E2 / (Km_on[1] + E2)\n    v3_on  = k_cat[2] * E2_P * E3 / (Km_on[2] + E3)\n\n    v1_off = Vmax_off[0] * E1_P / (Km_off[0] + E1_P)\n    v2_off = Vmax_off[1] * E2_P / (Km_off[1] + E2_P)\n    v3_off = Vmax_off[2] * E3_P / (Km_off[2] + E3_P)\n\n    return [v1_on - v1_off, v2_on - v2_off, v3_on - v3_off]\n```\n:::\n\n\n::: {#telluruim-aside .cell execution_count=2}\n``` {.python .cell-code}\n# For reference: this is how the same kind of model would instead be\n# imported from a published, curated SBML file in the BioModels\n# Database using Tellurium, rather than hand-built from kinetic theory.\n# Not run as part of this analysis — shown for completeness against\n# the standard systems-biology toolchain.\n\nimport tellurium as te\n\nmodel = te.loadSBMLModel(\"BIOMD0000000009.xml\")  # example BioModels ID\nresult = model.simulate(0, 200, 500)\nmodel.plot(result)\n```\n:::\n\n\n## 3. Time-Course Simulation\n\nWith the input signal held at a fixed level (a step input turned on at $t=0$), the three tiers activate in sequence, each lagging behind the one upstream of it.\n\n::: {#time-course .cell execution_count=3}\n``` {.python .cell-code}\ndef step_signal(level):\n    return lambda t: level if t >= 0 else 0.0\n\nS_level = 0.3\nsol = solve_ivp(\n    cascade_ode, t_span=(0, 60), y0=[0, 0, 0],\n    args=(step_signal(S_level), k_cat, Km_on, Km_off, Vmax_off, E_total),\n    method=\"LSODA\", dense_output=True, max_step=0.5\n)\n\nt_plot = np.linspace(0, 60, 300)\ny_plot = sol.sol(t_plot)\n```\n:::\n\n\n::: {#cell-time-course-plot .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nlabels = [\"Tier 1 (E1-P)\", \"Tier 2 (E2-P)\", \"Tier 3 (E3-P)\"]\ncolors = [\"#4DBBD5\", \"#3C5488\", \"#E64B35\"]\nfor i in range(3):\n    ax.plot(t_plot, y_plot[i], label=labels[i], color=colors[i], linewidth=2)\nax.set_xlabel(\"Time\")\nax.set_ylabel(\"Active (phosphorylated) fraction\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Activation time course for each cascade tier following a step input signal](signaling-pathway-ode-final_files/figure-html/time-course-plot-output-1.png){#time-course-plot width=758 height=470}\n:::\n:::\n\n\nThe delay visible between tiers — tier 2 rising only once tier 1 has built up, tier 3 only once tier 2 has — is the cascade's signal propagation time, and it's a direct, testable consequence of the model structure rather than an assumption. Each tier also settles to its own steady-state activation level, which is what Section 4 systematically maps out as a function of input strength.\n\n## 4. Steady-State Dose-Response and Ultrasensitivity\n\nRather than one fixed input level, sweeping the input signal across a range and recording each tier's steady-state activation traces out a dose-response curve — the pathway's fundamental input-output relationship.\n\n::: {#dose-response .cell execution_count=5}\n``` {.python .cell-code}\ndef steady_state(S_level, k_cat, Km_on, Km_off, Vmax_off, E_total, t_max=300):\n    sol = solve_ivp(\n        cascade_ode, t_span=(0, t_max), y0=[0, 0, 0],\n        args=(step_signal(S_level), k_cat, Km_on, Km_off, Vmax_off, E_total),\n        method=\"LSODA\"\n    )\n    return sol.y[:, -1]\n\nS_range = np.logspace(-3, 2, 50)\nsteady_states = np.array([\n    steady_state(S, k_cat, Km_on, Km_off, Vmax_off, E_total) for S in S_range\n])\n\ndose_response_df = pd.DataFrame(\n    steady_states, columns=[\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"]\n)\ndose_response_df[\"S\"] = S_range\n```\n:::\n\n\n::: {#cell-dose-response-plot .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nfor col, label, color in zip(\n    [\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"], labels, colors\n):\n    ax.plot(dose_response_df[\"S\"], dose_response_df[col],\n            label=label, color=color, linewidth=2, marker=\"o\", markersize=3)\nax.set_xscale(\"log\")\nax.set_xlabel(\"Input signal strength (S)\")\nax.set_ylabel(\"Steady-state active fraction\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Steady-state dose-response curves for each cascade tier, input signal on a log scale](signaling-pathway-ode-final_files/figure-html/dose-response-plot-output-1.png){#dose-response-plot width=758 height=468}\n:::\n:::\n\n\nIf the cascade amplifies ultrasensitivity as it propagates — which is the entire reason cascades are a common motif in cell signaling rather than a single ultrasensitive enzyme doing the whole job — tier 3's curve should look visibly steeper (more switch-like) than tier 1's. Section 5 puts a number on exactly how much steeper.\n\n## 5. Quantifying Ultrasensitivity: Hill Coefficient Fitting\n\nA Hill function, $E^P(S) = E_{tot} \\cdot S^n / (K^n + S^n)$, is the standard way to summarise a sigmoidal dose-response curve with a single ultrasensitivity metric: the Hill coefficient $n$. $n = 1$ is a simple hyperbolic (graded, Michaelis-Menten-like) response; $n > 1$ is sigmoidal; larger $n$ means a sharper, more switch-like transition.\n\n::: {#cell-hill-fit .cell execution_count=7}\n``` {.python .cell-code}\ndef hill_function(S, Vmax, K, n):\n    return Vmax * S**n / (K**n + S**n)\n\ndef fit_hill(S_values, output_values, label=\"\"):\n    \"\"\"Fit a Hill function, with wide-enough bounds to accommodate a\n    right-shifted or attenuated curve, and a clear failure message\n    instead of a crash if the fit genuinely can't converge.\"\"\"\n    try:\n        popt, _ = curve_fit(\n            hill_function, S_values, output_values,\n            p0=[max(output_values.max(), 0.01), np.median(S_values), 2.0],\n            maxfev=30000, bounds=([0, 1e-6, 0.1], [2, 100, 20])\n        )\n        return {\"Vmax\": popt[0], \"K\": popt[1], \"n\": popt[2]}\n    except RuntimeError as e:\n        print(f\"Hill fit did not converge for {label}: {e}\")\n        return {\"Vmax\": np.nan, \"K\": np.nan, \"n\": np.nan}\n\nhill_fits = {}\nfor col in [\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"]:\n    hill_fits[col] = fit_hill(dose_response_df[\"S\"], dose_response_df[col], label=col)\n\nhill_df = pd.DataFrame(hill_fits).T\nhill_df.index = [\"Tier 1\", \"Tier 2\", \"Tier 3\"]\nhill_df\n```\n\n::: {#hill-fit .cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Vmax</th>\n      <th>K</th>\n      <th>n</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Tier 1</th>\n      <td>0.991376</td>\n      <td>0.499368</td>\n      <td>7.60809</td>\n    </tr>\n    <tr>\n      <th>Tier 2</th>\n      <td>0.955120</td>\n      <td>0.504204</td>\n      <td>20.00000</td>\n    </tr>\n    <tr>\n      <th>Tier 3</th>\n      <td>0.953275</td>\n      <td>0.506049</td>\n      <td>20.00000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-hill-plot .cell execution_count=8}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 4))\nax.bar(hill_df.index, hill_df[\"n\"], color=colors, alpha=0.85)\nax.axhline(1, color=\"grey\", linestyle=\"--\", linewidth=0.8, label=\"n = 1 (graded)\")\nax.set_ylabel(\"Fitted Hill coefficient (n)\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Hill coefficient (ultrasensitivity) by cascade tier](signaling-pathway-ode-final_files/figure-html/hill-plot-output-1.png){#hill-plot width=566 height=374}\n:::\n:::\n\n\nThe fitted values show the amplification claim playing out, and then some: tier 1's Hill coefficient came out at 7.61, already well past the graded regime, and tiers 2 and 3 both hit 20.00 — the upper edge of the bound placed on the fit. That's worth being precise about rather than reporting 20.00 as a clean result: hitting a bound means the fit didn't converge to an interior optimum, it means the true Hill coefficient for tiers 2 and 3 is *at least* 20, possibly considerably higher, and this particular three-parameter Hill function isn't able to pin down exactly how high once the response is this close to a step function. If anything, that's a stronger statement about ultrasensitivity than a precise number would have been — by tier 2, the cascade's response to its input is already close to binary.\n\n::: {.callout-important title=\"This result depends on a kinetic regime, not just a topology\"}\nCascading enzymatic steps does not automatically produce ultrasensitivity. It does so specifically when each tier's Michaelis constants are small relative to that tier's total protein concentration — the \"zero-order\" regime, where enzymes operate near saturation. If the Km values are instead comparable to or larger than the total protein pool, the same cascade topology produces an essentially graded, non-switch-like response. Section 6 demonstrates this explicitly rather than treating ultrasensitivity as a property of cascades in general.\n:::\n\n## 6. Assumption Check: Zero-Order vs. First-Order Kinetic Regime\n\n::: {#cell-regime-comparison .cell execution_count=9}\n``` {.python .cell-code}\n# Zero-order regime: Km << E_total (already the parameters used above)\nKm_on_zero_order  = np.array([0.05, 0.05, 0.05])\nKm_off_zero_order = np.array([0.05, 0.05, 0.05])\n\n# First-order regime: Km >> E_total — enzymes are far from saturation\nKm_on_first_order  = np.array([5.0, 5.0, 5.0])\nKm_off_first_order = np.array([5.0, 5.0, 5.0])\n\ndef compute_dose_response(Km_on_set, Km_off_set):\n    ss = np.array([\n        steady_state(S, k_cat, Km_on_set, Km_off_set, Vmax_off, E_total)\n        for S in S_range\n    ])\n    return pd.DataFrame(ss, columns=[\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"])\n\ndr_zero_order  = compute_dose_response(Km_on_zero_order, Km_off_zero_order)\ndr_first_order = compute_dose_response(Km_on_first_order, Km_off_first_order)\n\nregime_comparison = pd.DataFrame({\n    \"Zero-order (Km << E_total)\": [\n        fit_hill(S_range, dr_zero_order[c], label=f\"zero-order {c}\")[\"n\"]\n        for c in [\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"]\n    ],\n    \"First-order (Km >> E_total)\": [\n        fit_hill(S_range, dr_first_order[c], label=f\"first-order {c}\")[\"n\"]\n        for c in [\"Tier1_P\", \"Tier2_P\", \"Tier3_P\"]\n    ],\n}, index=[\"Tier 1\", \"Tier 2\", \"Tier 3\"])\n\nregime_comparison\n```\n\n::: {#regime-comparison .cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Zero-order (Km &lt;&lt; E_total)</th>\n      <th>First-order (Km &gt;&gt; E_total)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Tier 1</th>\n      <td>7.60809</td>\n      <td>1.080781</td>\n    </tr>\n    <tr>\n      <th>Tier 2</th>\n      <td>20.00000</td>\n      <td>1.102488</td>\n    </tr>\n    <tr>\n      <th>Tier 3</th>\n      <td>20.00000</td>\n      <td>1.107444</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-regime-plot .cell execution_count=10}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nax.plot(S_range, dr_zero_order[\"Tier3_P\"], label=\"Zero-order (Km << E_total)\",\n        color=\"#E64B35\", linewidth=2, marker=\"o\", markersize=3)\nax.plot(S_range, dr_first_order[\"Tier3_P\"], label=\"First-order (Km >> E_total)\",\n        color=\"#4DBBD5\", linewidth=2, marker=\"o\", markersize=3)\nax.set_xscale(\"log\")\nax.set_xlabel(\"Input signal strength (S)\")\nax.set_ylabel(\"Tier 3 steady-state active fraction\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Tier 3 dose-response curve under the zero-order vs. first-order kinetic regime](signaling-pathway-ode-final_files/figure-html/regime-plot-output-1.png){#regime-plot width=758 height=468}\n:::\n:::\n\n\n::: {.callout-note title=\"Why the kinetic regime matters more than cascade depth\"}\nThe contrast is stark, and it confirms the theory cleanly. In the first-order regime, Hill coefficients sit at 1.08, 1.10, and 1.11 across tiers 1 through 3 — barely above the n = 1 graded baseline, with only a slight uptick tier to tier. In the zero-order regime — same topology, same total protein levels, same phosphatase activity, only the Michaelis constants changed — the coefficients are 7.61, ≥20, and ≥20. The entire ultrasensitivity result from Section 5 depends on that one change. It's also worth noting what the first-order numbers say on their own: the cascade structure itself contributes a small amount of steepening even without zero-order kinetics (1.08 → 1.11 across three tiers), but it's a minor effect next to what the kinetic regime contributes. Ultrasensitivity here is overwhelmingly a property of operating near enzyme saturation, not of chaining reactions in series.\n:::\n\n## 7. Parameter Sensitivity Analysis: Finding the Weakest Link\n\nEvery kinetic parameter in this model is, in principle, something a drug could perturb — a kinase inhibitor reduces an effective $k_{cat}$, a phosphatase activator raises a $V_{off}$. Local sensitivity analysis asks: for a small perturbation to each parameter, how much does pathway output move? The parameter the output is most sensitive to is the strongest candidate drug target, because a small effect on that parameter produces the largest effect on the pathway.\n\nSensitivity is evaluated at the tier-3 EC50 — the input level at half-maximal tier-3 activation — since that is where the dose-response curve is steepest and therefore where a given perturbation is most likely to produce a detectable change in output.\n\n::: {#cell-sensitivity-setup .cell execution_count=11}\n``` {.python .cell-code}\n# Reference input: tier 3's EC50 from the zero-order regime fit above\nS_ref = hill_fits[\"Tier3_P\"][\"K\"]\n\ndef tier3_output_at_Sref(k_cat, Km_on, Km_off, Vmax_off, E_total, S_ref):\n    return steady_state(S_ref, k_cat, Km_on, Km_off, Vmax_off, E_total)[2]\n\nbaseline_output = tier3_output_at_Sref(k_cat, Km_on, Km_off, Vmax_off, E_total, S_ref)\n\n# Parameters under test: catalytic rates, phosphatase Vmax, and Km_on/Km_off\n# for all three tiers. Total protein levels are deliberately excluded —\n# a drug in the classical sense perturbs an enzyme's kinetics, not the\n# cell's total expression of that enzyme, so restricting the search to\n# kinetic parameters keeps the ranking pharmacologically interpretable.\nparam_specs = []\nfor i in range(3):\n    param_specs.append((f\"k_cat[{i+1}]\", \"k_cat\", i))\n    param_specs.append((f\"Vmax_off[{i+1}]\", \"Vmax_off\", i))\n    param_specs.append((f\"Km_on[{i+1}]\", \"Km_on\", i))\n    param_specs.append((f\"Km_off[{i+1}]\", \"Km_off\", i))\n\nperturbation = 0.05  # ±5%\nsensitivities = {}\n\nfor name, array_name, idx in param_specs:\n    params = {\n        \"k_cat\": k_cat.copy(), \"Vmax_off\": Vmax_off.copy(),\n        \"Km_on\": Km_on.copy(), \"Km_off\": Km_off.copy()\n    }\n\n    params_up = {k: v.copy() for k, v in params.items()}\n    params_up[array_name][idx] *= (1 + perturbation)\n    output_up = tier3_output_at_Sref(\n        params_up[\"k_cat\"], params_up[\"Km_on\"], params_up[\"Km_off\"],\n        params_up[\"Vmax_off\"], E_total, S_ref\n    )\n\n    params_down = {k: v.copy() for k, v in params.items()}\n    params_down[array_name][idx] *= (1 - perturbation)\n    output_down = tier3_output_at_Sref(\n        params_down[\"k_cat\"], params_down[\"Km_on\"], params_down[\"Km_off\"],\n        params_down[\"Vmax_off\"], E_total, S_ref\n    )\n\n    # Normalised local sensitivity coefficient: (%change in output) / (%change in parameter)\n    pct_change_output = (output_up - output_down) / baseline_output\n    pct_change_param = 2 * perturbation\n    sensitivities[name] = pct_change_output / pct_change_param\n\nsensitivity_df = pd.DataFrame.from_dict(\n    sensitivities, orient=\"index\", columns=[\"sensitivity\"]\n).sort_values(\"sensitivity\", key=abs, ascending=False)\n\nsensitivity_df\n```\n\n::: {#sensitivity-setup .cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>sensitivity</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>k_cat[1]</th>\n      <td>10.537423</td>\n    </tr>\n    <tr>\n      <th>Vmax_off[1]</th>\n      <td>-10.523593</td>\n    </tr>\n    <tr>\n      <th>k_cat[2]</th>\n      <td>2.835838</td>\n    </tr>\n    <tr>\n      <th>Vmax_off[2]</th>\n      <td>-2.568585</td>\n    </tr>\n    <tr>\n      <th>Km_on[1]</th>\n      <td>-0.866866</td>\n    </tr>\n    <tr>\n      <th>Km_off[1]</th>\n      <td>0.775844</td>\n    </tr>\n    <tr>\n      <th>k_cat[3]</th>\n      <td>0.514510</td>\n    </tr>\n    <tr>\n      <th>Vmax_off[3]</th>\n      <td>-0.507074</td>\n    </tr>\n    <tr>\n      <th>Km_on[2]</th>\n      <td>-0.201890</td>\n    </tr>\n    <tr>\n      <th>Km_on[3]</th>\n      <td>-0.141425</td>\n    </tr>\n    <tr>\n      <th>Km_off[2]</th>\n      <td>0.111374</td>\n    </tr>\n    <tr>\n      <th>Km_off[3]</th>\n      <td>0.027108</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-sensitivity-plot .cell execution_count=12}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 6))\nsensitivity_df_sorted = sensitivity_df.reindex(\n    sensitivity_df[\"sensitivity\"].abs().sort_values().index\n)\nbar_colors = [\"#E64B35\" if v > 0 else \"#4DBBD5\" for v in sensitivity_df_sorted[\"sensitivity\"]]\nax.barh(sensitivity_df_sorted.index, sensitivity_df_sorted[\"sensitivity\"], color=bar_colors, alpha=0.85)\nax.axvline(0, color=\"grey\", linewidth=0.8)\nax.set_xlabel(\"Normalised sensitivity coefficient\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Normalised local sensitivity coefficients for tier-3 output, ranked by magnitude — the top bar is the model's 'weakest link'](signaling-pathway-ode-final_files/figure-html/sensitivity-plot-output-1.png){#sensitivity-plot width=662 height=566}\n:::\n:::\n\n\nThe ranking has a real surprise in it. The two largest sensitivities by a wide margin are tier 1's own parameters — k_cat[1] at 10.54 and Vmax_off[1] at -10.52 — roughly four times the magnitude of tier 2's parameters and roughly twenty times tier 3's, even though the output being measured is tier 3's activation. That's the opposite of the naive intuition that the enzyme closest to the readout should matter most.\n\n::: {.callout-important title=\"The counterintuitive result: tier 1 dominates, not tier 3\"}\nThe mechanism is worth spelling out because it's genuinely instructive: tiers 2 and 3 are operating deep in the zero-order regime, which by Section 5's own result means they sit close to a step function — already near-fully committed to on or off at the reference input. A small percentage change to an already-saturated tier's own kinetics has little room to move its output further, precisely because it's already near its ceiling or floor. Tier 1, by contrast, is the one tier still sitting on the graded part of its own response curve at this input level — it's the actual point in the cascade where continuous information about signal strength is still being encoded before the downstream switches commit. Perturb the encoder and the whole cascade's decision shifts; perturb an already-decided switch and mostly nothing happens. The near-equal, opposite-signed magnitudes of k_cat[1] and Vmax_off[1] are a good internal consistency check on top of that: increasing the kinase and decreasing its opposing phosphatase should have symmetric effects on tier 1's own steady state, and they do.\n\nPractically, this means the best drug target in this model isn't the terminal kinase most directly tied to the pathway's biological output — it's the first tier, the one still translating signal strength into a graded response before the cascade's downstream switches lock in.\n:::\n\n## Takeaways\n\n::: {.callout-important title=\"Key findings\" icon=\"false\"}\n- Ultrasensitivity amplifies sharply across the cascade: Hill coefficients of 7.61, ≥20, and ≥20 for tiers 1 through 3. The tier 2 and 3 fits hit the bound placed on them, meaning the true values are at least that high — by tier 2, the response is already close to a step function.\n- The zero-order vs. first-order regime comparison is the assumption check most public-facing explanations of MAPK-style switches skip entirely, and the contrast here is stark: the same topology drops from Hill coefficients ≥20 to 1.08-1.11 — barely above graded — when the Michaelis constants are moved out of the zero-order regime. Ultrasensitivity is overwhelmingly a property of the kinetic regime, not the cascade structure; the structure alone contributes only a small residual steepening (1.08 → 1.11 across tiers).\n- The sensitivity ranking held a real surprise: tier 1's own parameters (k_cat[1], Vmax_off[1]) dominate by roughly 4x over tier 2 and 20x over tier 3 — even though tier 3 is the measured output. The mechanism is that tiers 2 and 3 are already saturated switches with little room left to move, while tier 1 is the one part of the cascade still encoding graded information about signal strength. The best drug target in this model is the first tier, not the one closest to the biological readout.\n- This is a simplified, single-phosphorylation-per-tier cascade. The real MAPK pathway uses dual phosphorylation at the MEK and ERK tiers, which produces even sharper ultrasensitivity than shown here — the qualitative results (amplification across tiers, regime-dependence, upstream sensitivity dominance) should hold either way, but the absolute Hill coefficients here are a lower bound on the real pathway's behaviour, not a literal prediction of it.\n:::\n\n#SystemsBiology #SignalTransduction #MAPK #ODEModeling #DrugTarget #SciPy #Python #ComputationalBiology\n\n",
    "supporting": [
      "signaling-pathway-ode-final_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}