{
  "hash": "c6c15e3a5f5307f649d37f9139546f49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayesian Hierarchical Negative Binomial Mixed Models for Longitudinal RNA-seq\"\nauthor: \"Peekei\"\ndate: \"2026-07-14\"\ndescription: \"An R-based Bayesian biostatistics deep dive: building a three-layer model (negative binomial GLM, mixed-effects repeated-measures structure, Bayesian hierarchical shrinkage in Stan) for longitudinal RNA-seq, showing exactly what each layer fixes and where the real estimation gains come from.\"\ncategories: [Biostatistics, Bayesian, RNA-seq, Mixed Models, RStats, Bioinformatics]\nformat:\n  html:\n    toc: true\n    toc-float: true\n    code-fold: true\n    code-summary: \"Show code\"\n    fig-cap-location: bottom\n---\n\n\n\n## 1. Motivation\n\nMost RNA-seq analyses treat each timepoint independently. That's fine when the study design actually is cross-sectional — different subjects at each timepoint — but falls apart the moment the same subjects are measured repeatedly over a treatment course. Repeated measures introduce within-subject correlation that a standard GLM ignores, and ignoring it means the standard errors on your treatment-over-time estimates are wrong, not merely imprecise.\n\nFix the correlation structure with a mixed model and you've solved that problem, but you've introduced another: with many genes and modest sample sizes, per-gene fixed-effect estimates of temporal trajectories are noisy. A gene measured in eight subjects over three timepoints doesn't have much information to estimate its own trajectory independently of every other gene. This is exactly the setting where a Bayesian hierarchical layer earns its place — borrowing information across genes to shrink noisy trajectory estimates toward a population mean, in proportion to how much each gene's own data can push back.\n\nThree layers, one model. The GLM handles the count distribution. The mixed model handles the repeated measures. The Bayesian hierarchy handles the small-n / many-genes estimation problem. None of them is optional given this data structure, and that's the argument this piece makes by building each layer in sequence and showing what goes wrong when a layer is missing.\n\n## 2. Simulated Longitudinal RNA-seq Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_subjects <- 8\nn_genes    <- 120\ntimepoints <- c(0, 4, 12)   # weeks: baseline, mid-treatment, end of treatment\nn_times    <- length(timepoints)\n\n# True temporal slopes per gene: mostly null, a subset genuinely trending\ntrue_slope <- c(\n  rnorm(80, mean =  0.00, sd = 0.05),\n  rnorm(25, mean =  0.12, sd = 0.04),\n  rnorm(15, mean = -0.15, sd = 0.04)\n)\ntrue_slope <- sample(true_slope)\n\nsubject_re   <- rnorm(n_subjects, mean = 0, sd = 0.6)\nbaseline_log <- rnorm(n_genes,    mean = 5.2, sd = 1.1)\ngene_disp    <- rgamma(n_genes,   shape = 3, rate = 8)\n\nsim_data <- expand_grid(\n  subject = 1:n_subjects,\n  gene    = 1:n_genes,\n  week    = timepoints\n) %>%\n  mutate(\n    log_mu = baseline_log[gene] + true_slope[gene] * week + subject_re[subject],\n    mu     = exp(log_mu),\n    size   = 1 / gene_disp[gene],\n    count  = rnegbin(n(), mu = mu, theta = size)\n  )\n\nsim_data %>%\n  group_by(week) %>%\n  summarise(\n    n_obs        = n(),\n    mean_count   = round(mean(count), 1),\n    median_count = median(count),\n    pct_zero     = round(mean(count == 0) * 100, 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n   week n_obs mean_count median_count pct_zero\n  <dbl> <int>      <dbl>        <dbl>    <dbl>\n1     0   960       434.         148       0.3\n2     4   960       462.         158       0.1\n3    12   960       641.         170.      0.4\n```\n\n\n:::\n:::\n\n\n8 subjects, 120 genes, 3 timepoints (weeks 0, 4, 12) — 2880 total observations. True temporal trajectories were generated at the gene level: 80 genuinely null, 25 upregulated over the treatment course, 15 downregulated, with gene-specific negative binomial dispersion and subject-level random intercepts baked into the data-generating process. A model that ignores either the NB structure or the repeated-measures correlation is misspecified from the start.\n\n## 3. Layer 1 — Overdispersion Check: Why Poisson Isn't Enough\n\nBefore fitting anything, the count distribution needs checking. Poisson regression assumes mean equals variance — RNA-seq counts virtually never satisfy this, but it's worth demonstrating with the actual data rather than asserting it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_eg  <- sim_data %>% filter(gene == 5)\n\nfit_pois <- glm(count ~ week, data = gene_eg, family = poisson)\nfit_nb   <- glm.nb(count ~ week, data = gene_eg)\n\ndispersion_ratio <- deviance(fit_pois) / df.residual(fit_pois)\ntheta_est        <- fit_nb$theta\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_eg %>%\n  mutate(\n    Poisson             = fitted(fit_pois),\n    `Negative Binomial` = fitted(fit_nb)\n  ) %>%\n  pivot_longer(cols = c(Poisson, `Negative Binomial`),\n               names_to = \"model\", values_to = \"fitted\") %>%\n  ggplot(aes(x = week)) +\n  geom_point(aes(y = count), alpha = 0.6, color = \"#3C5488\") +\n  geom_line(aes(y = fitted, color = model), linewidth = 1) +\n  scale_color_manual(values = c(\"Poisson\" = \"#E64B35\", \"Negative Binomial\" = \"#00A087\")) +\n  labs(x = \"Week\", y = \"Count\", color = \"Model\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Observed counts vs. Poisson and negative binomial fitted values for a representative gene](bayesian-longitudinal-glm-final_files/figure-html/overdispersion-plot-1.png){width=672}\n:::\n:::\n\n\nFor this gene, the Poisson deviance-to-df ratio is 1586.85 — not slightly above 1, but three orders of magnitude above it. A well-fitting Poisson model would produce a ratio near 1; this one produces 1587, which is what extreme overdispersion actually looks like in practice rather than in a textbook example. The negative binomial absorbs this by adding a gene-specific dispersion parameter, estimated here as θ = 1.28. Every subsequent layer in this analysis uses NB counts for this reason — the Poisson likelihood isn't a conservative approximation here, it's structurally wrong.\n\n## 4. Layer 2 — Mixed Effects Structure: Handling Repeated Measures\n\nA standard NB GLM treats every observation as independent. For repeated-measures data that's wrong — observations from the same subject across three timepoints are correlated in ways observations from different subjects aren't. Ignoring that correlation underestimates standard errors on the time slope.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_mm   <- sim_data %>% filter(gene == 12) %>% mutate(subject_f = factor(subject))\n\nglm_fixed <- glm.nb(count ~ week, data = gene_mm)\nglmm_fit  <- glmer.nb(count ~ week + (1 | subject_f), data = gene_mm)\n\nglm_se    <- summary(glm_fixed)$coefficients[\"week\", \"Std. Error\"]\nglmm_se   <- sqrt(diag(vcov(glmm_fit)))[\"week\"]\nse_ratio  <- glmm_se / glm_se\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngene_mm %>%\n  ggplot(aes(x = week, y = count, group = subject_f, color = subject_f)) +\n  geom_line(alpha = 0.7) +\n  geom_point(size = 2) +\n  scale_color_brewer(palette = \"Dark2\", name = \"Subject\") +\n  labs(x = \"Week\", y = \"Count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Subject-level count trajectories for a representative gene — within-subject clustering is visible across timepoints](bayesian-longitudinal-glm-final_files/figure-html/re-plot-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Why the SE went down, not up\"}\nStandard error on the time slope from the fixed-effects GLM: 0.031. From the mixed model with subject random intercepts: 0.015 — a ratio of 0.49, meaning the mixed model SE is actually *smaller* here, not larger as is sometimes assumed. This is worth being precise about: the direction of the SE change when adding random effects depends on the specific covariance structure of the data. When between-subject variability happens to be confounded with the time predictor in the fixed-effects model — inflating the slope's apparent noise — adding a random intercept that correctly absorbs that between-subject variance can sharpen the slope estimate rather than widen it. Gene 12 is a case of that. The general point stands: the fixed-effects GLM is making an incorrect independence assumption, and the mixed model is correcting it, even if the correction narrows rather than widens the SE for this particular gene.\n:::\n\n## 5. Layer 3 — Bayesian Hierarchical Model\n\nThe mixed-effects NB model handles one gene at a time. A Bayesian hierarchical model fits all genes jointly, letting the population distribution of temporal slopes be estimated from the data itself. Genes with weak individual signal get shrunk toward the population mean slope; genes with strong trajectories resist that pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstan_code <- \"\ndata {\n  int<lower=1> n_obs;\n  int<lower=1> n_genes;\n  int<lower=1> n_subjects;\n  array[n_obs] int<lower=0> counts;\n  vector[n_obs] week;\n  array[n_obs] int<lower=1, upper=n_genes>    gene_id;\n  array[n_obs] int<lower=1, upper=n_subjects> subject_id;\n}\nparameters {\n  real mu_slope;\n  real<lower=0> sigma_slope;\n  vector[n_genes] alpha;\n  vector[n_genes] beta;\n  vector[n_subjects] u_subject;\n  real<lower=0> sigma_subject;\n  vector<lower=0>[n_genes] phi;\n}\nmodel {\n  mu_slope      ~ normal(0, 0.5);\n  sigma_slope   ~ normal(0, 0.3);\n  sigma_subject ~ normal(0, 0.5);\n  alpha         ~ normal(5, 2);\n  beta          ~ normal(mu_slope, sigma_slope);\n  u_subject     ~ normal(0, sigma_subject);\n  phi           ~ gamma(2, 0.5);\n\n  for (i in 1:n_obs) {\n    real log_mu_i = alpha[gene_id[i]] +\n                    beta[gene_id[i]] * week[i] +\n                    u_subject[subject_id[i]];\n    counts[i] ~ neg_binomial_2_log(log_mu_i, phi[gene_id[i]]);\n  }\n}\n\"\nstan_file <- write_stan_file(stan_code)\nstan_mod  <- cmdstan_model(stan_file)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstan_data <- list(\n  n_obs      = nrow(sim_data),\n  n_genes    = n_genes,\n  n_subjects = n_subjects,\n  counts     = sim_data$count,\n  week       = sim_data$week,\n  gene_id    = sim_data$gene,\n  subject_id = sim_data$subject\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_path <- \"bayesian_longitudinal_fit.rds\"\n\nif (file.exists(fit_path)) {\n  message(\"Loading cached Stan fit — skipping sampling.\")\n  fit <- readRDS(fit_path)\n} else {\n  message(\"No cached fit found — running sampler now.\")\n  fit <- stan_mod$sample(\n    data            = stan_data,\n    chains          = 4,\n    parallel_chains = 4,\n    iter_warmup     = 1000,\n    iter_sampling   = 1000,\n    seed            = 412,\n    adapt_delta     = 0.90,\n    refresh         = 0\n  )\n  fit$save_object(file = fit_path)\n  message(\"Fit saved to disk.\")\n}\n\n# Flat draws matrix used throughout the rest of this article — columns are\n# named e.g. \"beta[12]\", \"u_subject[3]\" following Stan's array-flattening\n# convention. Converted to a plain base-R matrix (stripping posterior's\n# draws_matrix class) so downstream arithmetic — e.g. inside MASS::rnegbin()\n# — doesn't run into that class's own stricter Ops methods on subsetted rows.\npost_matrix <- as_draws_matrix(fit$draws())\npost_matrix <- matrix(\n  as.numeric(post_matrix),\n  nrow = nrow(post_matrix),\n  dimnames = dimnames(post_matrix)\n)\n```\n:::\n\n\nThe key structural line is `beta[g] ~ normal(mu_slope, sigma_slope)`: every gene's temporal slope is drawn from a shared population distribution whose mean and spread are estimated from all 120 genes simultaneously. `u_subject[s] ~ normal(0, sigma_subject)` handles the repeated-measures correlation — each subject carries a persistent log-scale offset across genes and timepoints, absorbing the between-subject variability the fixed-effects GLM would otherwise misattribute to time.\n\n## 6. MCMC Convergence Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhyper_pars <- c(\"mu_slope\", \"sigma_slope\", \"sigma_subject\")\nconv_table <- fit$summary(variables = hyper_pars)\nconv_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 10\n  variable         mean  median      sd     mad       q5    q95  rhat ess_bulk\n  <chr>           <dbl>   <dbl>   <dbl>   <dbl>    <dbl>  <dbl> <dbl>    <dbl>\n1 mu_slope      0.00653 0.00656 0.00928 0.00936 -0.00860 0.0214  1.00    6690.\n2 sigma_slope   0.0920  0.0917  0.00652 0.00647  0.0820  0.103   1.00    6731.\n3 sigma_subject 0.645   0.621   0.150   0.135    0.442   0.925   1.00    4833.\n# ℹ 1 more variable: ess_tail <dbl>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_summary <- fit$summary()\nall_rhat <- all_summary$rhat\nall_neff <- all_summary$ess_bulk\nmax_rhat <- max(all_rhat, na.rm = TRUE)\nmin_neff <- min(all_neff, na.rm = TRUE)\n\nmu_slope_est  <- conv_table$mean[conv_table$variable == \"mu_slope\"]\nsig_slope_est <- conv_table$mean[conv_table$variable == \"sigma_slope\"]\nsig_subj_est  <- conv_table$mean[conv_table$variable == \"sigma_subject\"]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_trace(fit$draws(variables = hyper_pars))\n```\n\n::: {.cell-output-display}\n![Trace plots for population-level hyperparameters across all four chains](bayesian-longitudinal-glm-final_files/figure-html/trace-plots-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrhat_df <- data.frame(rhat = all_rhat[!is.na(all_rhat)])\nggplot(rhat_df, aes(x = rhat)) +\n  geom_histogram(bins = 40, fill = \"#4DBBD5\", color = \"white\") +\n  geom_vline(xintercept = 1.01, linetype = \"dashed\", color = \"#E64B35\") +\n  labs(x = \"Rhat\", y = \"Count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Distribution of Rhat values across all monitored parameters — dashed line at 1.01](bayesian-longitudinal-glm-final_files/figure-html/rhat-plot-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Numbers below reflect the original rstan run\"}\nThe Rhat/ESS figures quoted in the prose below (1.017, 163, etc.) are from the original sampler run. `cmdstanr` uses the same NUTS algorithm and should reproduce essentially identical posteriors, but re-running with the new backend may shift these by a small amount — worth re-checking against your own render rather than trusting the hard-coded numbers here word for word.\n:::\n\nMaximum Rhat across all monitored parameters: 1.017. That's technically above the conventional 1.01 threshold, though barely — the hyperparameters themselves (mu_slope Rhat = 1.000, sigma_slope = 1.000, sigma_subject = 1.000) are clean, and the trace plots confirm stable mixing across all four chains with no drift or funnel collapse. The elevated maximum is coming from a handful of gene-level parameters, not the population-level quantities driving inference. More notable is the minimum bulk effective sample size of 163 — low relative to the 4000 post-warmup draws, which means some parameters are autocorrelated enough that the chains aren't mixing as freely as the trace plots suggest. This is a known feature of hierarchical NB models: the gene-level intercepts and the subject random effects can create posterior geometry that slows down exploration. In a publication context this would warrant either a longer run or reparameterization (non-centered parameterization for the gene-level slopes); for this analysis the hyperparameter ESS values are well above 3000 and the primary inferential targets are stable. Population-level estimates: mu_slope = 0.006, sigma_slope = 0.092, sigma_subject = 0.639.\n\n## 7. Posterior Predictive Check\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_draws_ppc <- 60\nppc_gene_id <- 10\n\nobs_counts <- sim_data %>% filter(gene == ppc_gene_id) %>% pull(count)\nobs_idx    <- which(sim_data$gene == ppc_gene_id)\nn_obs_gene <- length(obs_idx)\n\nalpha_mat <- post_matrix[, paste0(\"alpha[\", 1:n_genes, \"]\")]\nbeta_mat  <- post_matrix[, paste0(\"beta[\", 1:n_genes, \"]\")]\nu_mat     <- post_matrix[, paste0(\"u_subject[\", 1:n_subjects, \"]\")]\nphi_mat   <- post_matrix[, paste0(\"phi[\", 1:n_genes, \"]\")]\n\ndraw_idx <- sample(seq_len(nrow(post_matrix)), n_draws_ppc)\nppc_rep  <- matrix(NA, nrow = n_draws_ppc, ncol = n_obs_gene)\n\nfor (i in seq_along(draw_idx)) {\n  d <- draw_idx[i]\n  log_mu_vec   <- alpha_mat[d, ppc_gene_id] +\n                  beta_mat[d, ppc_gene_id] * sim_data$week[obs_idx] +\n                  u_mat[d, sim_data$subject[obs_idx]]\n  ppc_rep[i, ] <- rnegbin(n_obs_gene,\n                           mu    = exp(log_mu_vec),\n                           theta = phi_mat[d, ppc_gene_id])\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppc_dens_overlay(y = obs_counts, yrep = ppc_rep)\n```\n\n::: {.cell-output-display}\n![Posterior predictive check: observed count distribution vs. 60 replicated datasets for a representative gene](bayesian-longitudinal-glm-final_files/figure-html/ppc-plot-1.png){width=672}\n:::\n:::\n\n\nThe observed count density falls well within the envelope of posterior predictive replicates. The PPC is specifically checking whether the NB likelihood with gene-specific φ reproduces the overdispersion in the observed counts — a Poisson likelihood would produce replicated distributions that are too narrow relative to what was actually observed.\n\n## 8. Three-Stage Estimation Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stage 1: naive log-ratio of group means\nnaive_slopes <- sim_data %>%\n  group_by(gene, week) %>%\n  summarise(mean_count = mean(count) + 0.5, .groups = \"drop\") %>%\n  mutate(week_label = paste0(\"wk\", as.integer(week))) %>%\n  dplyr::select(-week) %>%\n  pivot_wider(names_from = week_label, values_from = mean_count) %>%\n  mutate(naive_slope = (log(wk12) - log(wk0)) / 12) %>%\n  dplyr::select(gene, naive_slope) %>%\n  arrange(gene)\n\n# Stage 2: per-gene NB GLM slope (no random effects)\nglm_slopes <- map(1:n_genes, function(g) {\n  dat   <- sim_data %>% filter(gene == g)\n  fit_g <- tryCatch(glm.nb(count ~ week, data = dat), error = function(e) NULL)\n  if (is.null(fit_g)) return(tibble(gene = g, glm_slope = NA_real_))\n  tibble(gene = g, glm_slope = coef(fit_g)[\"week\"])\n}) |> list_rbind()\n\n# Stage 3: Bayesian posterior means\nbayes_slopes <- tibble(\n  gene        = 1:n_genes,\n  bayes_slope = colMeans(beta_mat)\n)\n\ncomparison <- tibble(gene = 1:n_genes, true_slope = true_slope) %>%\n  left_join(naive_slopes, by = \"gene\") %>%\n  left_join(glm_slopes,   by = \"gene\") %>%\n  left_join(bayes_slopes, by = \"gene\")\n\nrmse_fn    <- function(est, truth) sqrt(mean((est - truth)^2, na.rm = TRUE))\nrmse_naive <- rmse_fn(comparison$naive_slope, comparison$true_slope)\nrmse_glm   <- rmse_fn(comparison$glm_slope,   comparison$true_slope)\nrmse_bayes <- rmse_fn(comparison$bayes_slope, comparison$true_slope)\n\ntibble(\n  Estimator = c(\"Naive (mean ratio)\", \"NB GLM (no RE)\", \"Bayesian hierarchical\"),\n  RMSE      = round(c(rmse_naive, rmse_glm, rmse_bayes), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Estimator               RMSE\n  <chr>                  <dbl>\n1 Naive (mean ratio)    0.0293\n2 NB GLM (no RE)        0.0283\n3 Bayesian hierarchical 0.0213\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison %>%\n  pivot_longer(cols = c(naive_slope, glm_slope, bayes_slope),\n               names_to = \"estimator\", values_to = \"estimate\") %>%\n  mutate(estimator = case_match(estimator,\n    \"naive_slope\" ~ \"Naive\",\n    \"glm_slope\"   ~ \"NB GLM\",\n    \"bayes_slope\" ~ \"Bayesian\")) %>%\n  mutate(estimator = factor(estimator, levels = c(\"Naive\", \"NB GLM\", \"Bayesian\"))) %>%\n  ggplot(aes(x = true_slope, y = estimate)) +\n  geom_point(alpha = 0.4, color = \"#3C5488\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"grey40\") +\n  facet_wrap(~estimator) +\n  labs(x = \"True slope\", y = \"Estimated slope\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![True vs. estimated temporal slopes across all genes, for all three estimators](bayesian-longitudinal-glm-final_files/figure-html/comparison-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npct_naive_to_bayes <- (rmse_naive - rmse_bayes) / rmse_naive * 100\npct_glm_to_bayes   <- (rmse_glm   - rmse_bayes) / rmse_glm   * 100\n```\n:::\n\n\nThree estimators, same ground truth. Naive RMSE = 0.0293. Per-gene NB GLM = 0.0283 — a small but real improvement from correct count modeling alone. Bayesian hierarchical = 0.0213, a 27.4% reduction from naive and 24.6% from the GLM. The gap between GLM and Bayesian is larger than the gap between naive and GLM, which tells you something about where the estimation problem actually lives in this dataset: the count distribution misspecification (Poisson vs. NB) matters, but the bigger source of noise is per-gene slope estimation with limited data, and that's what the hierarchical prior is addressing.\n\n## 9. Gene-Level Trajectory Illustration\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- comparison %>%\n  mutate(\n    abs_true   = abs(true_slope),\n    abs_shrink = abs(glm_slope - bayes_slope)\n  )\n\nnull_gene_id <- comparison %>%\n  filter(abs_true < 0.02) %>%\n  arrange(desc(abs_shrink)) %>%\n  slice(1) %>%\n  pull(gene)\n\nde_gene_id <- comparison %>%\n  filter(abs_true > 0.10) %>%\n  arrange(abs_shrink) %>%\n  slice(1) %>%\n  pull(gene)\n\nn_traj_draws  <- 200\nweek_seq      <- seq(0, 12, length.out = 50)\ndraw_idx_traj <- sample(seq_len(nrow(beta_mat)), n_traj_draws)\n\ntraj_data <- map(c(null_gene_id, de_gene_id), function(g) {\n  map(seq_along(draw_idx_traj), function(i) {\n    d <- draw_idx_traj[i]\n    tibble(\n      gene      = g,\n      week      = week_seq,\n      log_count = alpha_mat[d, g] + beta_mat[d, g] * week_seq,\n      draw      = i\n    )\n  }) |> list_rbind()\n}) |> list_rbind()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_label <- function(g, type) {\n  paste0(\"Gene \", g, \" (\", type, \", slope \\u2248 \", round(true_slope[g], 3), \")\")\n}\n\nobs_for_plot <- sim_data %>%\n  filter(gene %in% c(null_gene_id, de_gene_id)) %>%\n  mutate(gene_label = case_match(gene,\n    null_gene_id ~ make_label(null_gene_id, \"null\"),\n    de_gene_id   ~ make_label(de_gene_id,   \"DE\")))\n\ntraj_summary <- traj_data %>%\n  mutate(gene_label = case_match(gene,\n    null_gene_id ~ make_label(null_gene_id, \"null\"),\n    de_gene_id   ~ make_label(de_gene_id,   \"DE\"))) %>%\n  group_by(gene_label, week) %>%\n  summarise(\n    med = median(exp(log_count)),\n    lo  = quantile(exp(log_count), 0.05),\n    hi  = quantile(exp(log_count), 0.95),\n    .groups = \"drop\"\n  )\n\nggplot() +\n  geom_ribbon(data = traj_summary,\n              aes(x = week, ymin = lo, ymax = hi),\n              alpha = 0.25, fill = \"#4DBBD5\") +\n  geom_line(data = traj_summary,\n            aes(x = week, y = med),\n            color = \"#3C5488\", linewidth = 1) +\n  geom_jitter(data = obs_for_plot,\n              aes(x = week, y = count),\n              width = 0.3, alpha = 0.5, color = \"#E64B35\") +\n  facet_wrap(~gene_label, scales = \"free_y\") +\n  labs(x = \"Week\", y = \"Count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Posterior trajectory bands (90% interval) for a null gene and a genuinely DE gene, with observed counts overlaid](bayesian-longitudinal-glm-final_files/figure-html/traj-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_naive <- comparison %>% filter(gene == null_gene_id) %>% pull(naive_slope)\nnull_glm   <- comparison %>% filter(gene == null_gene_id) %>% pull(glm_slope)\nnull_bayes <- comparison %>% filter(gene == null_gene_id) %>% pull(bayes_slope)\nnull_true  <- true_slope[null_gene_id]\n\nde_naive   <- comparison %>% filter(gene == de_gene_id) %>% pull(naive_slope)\nde_glm     <- comparison %>% filter(gene == de_gene_id) %>% pull(glm_slope)\nde_bayes   <- comparison %>% filter(gene == de_gene_id) %>% pull(bayes_slope)\nde_true    <- true_slope[de_gene_id]\n```\n:::\n\n\nFor Gene 62 — truly null, true slope = -0.008 — the naive estimator gave -0.045, the GLM gave -0.047, and the Bayesian model pulled this to -0.011. The wide posterior band and flat trajectory are the model correctly expressing uncertainty rather than committing to a spurious direction driven by sampling noise.\n\nGene 94 — genuinely DE, true slope = 0.218 — goes the other way. Naive: 0.193, GLM: 0.19, Bayesian: 0.19. Barely any movement between estimators — this gene's signal is strong enough that its own likelihood dominates the population prior. The posterior band is tighter, the trajectory is directional, and the hierarchy adds almost nothing here except to confirm that the gene's individual data is carrying the weight.\n\n::: {.callout-tip title=\"Run this yourself\"}\nThe same three-layer approach — negative binomial structure, repeated-measures handling, and Bayesian hierarchical shrinkage across genes — is packaged as `fit_rnaseq_nb_pipeline()` in [`omicsuite`](https://github.com/Real-peekei/omicsuite), which fits via `brms` rather than hand-written Stan and returns convergence, dispersion, and per-gene shrinkage checks as a structured verdict table.\n:::\n\n## Takeaways\n\n::: {.callout-important title=\"Key findings\" icon=\"false\"}\n- Each modeling layer earns its place in the data structure: the negative binomial handles overdispersion the Poisson can't absorb, the random intercept correctly partitions between-subject variability the fixed-effects GLM misattributes to time, and the Bayesian hierarchy regularizes noisy gene-level slope estimates by borrowing across all 120 genes simultaneously.\n- The three-stage RMSE comparison — 0.029 (naive) → 0.028 (NB GLM) → 0.021 (Bayesian) — shows the largest single gain came from the Bayesian shrinkage step, not the count-model correction. Correct count modeling helps, but per-gene slope estimation with limited data is the bigger source of noise in this regime, and that's what the hierarchical prior addresses.\n- MCMC convergence was verified directly: maximum Rhat across all monitored parameters was 1.017 and the hyperparameter-level Rhats were all at or below 1.000. The minimum effective sample size of 163 across all parameters flags some autocorrelation in the gene-level intercepts — a known feature of hierarchical NB models with complex posterior geometry. The population-level quantities driving inference had ESS well above 3000 and are not affected.\n- The posterior predictive check confirmed the NB likelihood with gene-specific dispersion reproduces the observed count distribution's spread — a step convergence diagnostics alone cannot validate, and one that's skipped more often than it should be.\n- Shrinkage here is adaptive, not uniform: the degree to which a gene's estimate gets pulled toward the population mean is determined by the strength of that gene's own likelihood, not by any analyst-specified threshold.\n- The population-level hyperparameters (mu_slope, sigma_slope) are estimated from the data — the model learns both the typical trajectory across genes and the gene-to-gene variability around it, rather than treating either as a fixed tuning parameter.\n:::\n\n#Biostatistics #Bayesian #RNAseq #Genomics #LongitudinalData #MixedModels #GLM #Bioinformatics #RStats\n",
    "supporting": [
      "bayesian-longitudinal-glm-final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}