{
  "hash": "32a61e4a7ca1a27f488353315d0b1fb2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cox Proportional Hazards Modeling in a Simulated Oncology Trial\"\nauthor: \"Peekei\"\ndate: \"2026-07-13\"\ndescription: \"An R-based biostatistics deep dive: fitting and validating a Cox PH model on a simulated two-arm oncology trial — unadjusted vs. adjusted hazard ratios, proportional hazards diagnostics, martingale residuals for functional form, and concordance.\"\ncategories: [Biostatistics, Survival Analysis, RStats, Clinical Trials]\nformat:\n  html:\n    toc: true\n    toc-float: true\n    fig-cap-location: bottom\n---\n\n\n\n## 1. Motivation\n\nTime-to-event outcomes — death, disease progression, relapse — are the primary endpoints in most phase II/III oncology trials. They come with a structural complication ordinary regression can't handle: censoring. Patients leave a trial alive, get lost to follow-up, or simply haven't had the event by the data cutoff, and treating those patients as \"no event = longest survival,\" or dropping them outright, both bias the result. The Cox proportional hazards model gets around this by modeling the *hazard* — the instantaneous event rate conditional on survival to that point — without committing to a parametric shape for the baseline hazard itself.\n\nWhat follows fits and validates a Cox model on a simulated two-arm oncology trial. Treatment assignment is the primary inferential target; age and baseline ECOG performance status come along as adjustment covariates.\n\n## 2. Simulated Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\n\nn <- 300\ntreatment <- rbinom(n, 1, 0.5)\nage <- round(rnorm(n, mean = 60, sd = 10))\nage <- pmin(pmax(age, 30), 85)\necog <- sample(0:2, n, replace = TRUE, prob = c(0.5, 0.35, 0.15))\n\n# True hazard ratio for treatment ~0.65 (protective), age and ECOG as nuisance covariates\nlinpred <- 0.02 * (age - 60) + 0.5 * ecog - 0.43 * treatment\nbaseline_scale <- 8  # months, baseline median survival driver\n\nu <- runif(n)\nevent_time <- baseline_scale * (-log(u) / exp(linpred))^(1)\n\n# Administrative censoring at 24 months + independent random dropout\ncensor_time <- pmin(24, rexp(n, rate = 1/30))\ntime <- pmin(event_time, censor_time)\nstatus <- as.integer(event_time <= censor_time)\n\ntrial_data <- tibble(\n  id = 1:n,\n  time = round(time, 1),\n  status = status,\n  treatment = factor(treatment, labels = c(\"Control\", \"Treatment\")),\n  age = age,\n  ecog = factor(ecog, labels = c(\"0\", \"1\", \"2\"))\n)\n\ntrial_data %>%\n  group_by(treatment) %>%\n  summarise(\n    n = n(),\n    events = sum(status),\n    event_rate = round(mean(status), 2),\n    median_followup = round(median(time), 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  treatment     n events event_rate median_followup\n  <fct>     <int>  <int>      <dbl>           <dbl>\n1 Control     158    131       0.83             3.4\n2 Treatment   142     96       0.68             5.2\n```\n\n\n:::\n:::\n\n\nA cohort of 300 patients, randomized roughly 1:1 to control or treatment, followed for up to 24 months under administrative censoring plus random dropout. Event rates came out high in both arms — 83% in control, 68% in treatment — and median follow-up to event or censoring sits at just 3.4 months for control versus 5.2 for treatment. This is a fast-moving disease in the simulation: most patients who are going to have the event have it within the first several months, which is exactly the setting where a Cox model's constant-hazard-ratio assumption is most likely to be stressed, and exactly why Section 5 checks it directly rather than taking it on faith.\n\n## 3. Kaplan-Meier Curves by Treatment Arm\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm_fit <- survfit(Surv(time, status) ~ treatment, data = trial_data)\n\nggsurvplot(\n  km_fit,\n  data = trial_data,\n  pval = TRUE,\n  conf.int = TRUE,\n  risk.table = TRUE,\n  legend.title = \"Arm\",\n  xlab = \"Time (months)\",\n  ylab = \"Survival probability\",\n  palette = c(\"#E64B35\", \"#4DBBD5\")\n)\n```\n\n::: {.cell-output-display}\n![Kaplan-Meier survival curves by treatment arm](survival-analysis-final_files/figure-html/km-fit-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogrank <- survdiff(Surv(time, status) ~ treatment, data = trial_data)\nlogrank_p <- 1 - pchisq(logrank$chisq, df = 1)\nlogrank_p\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0002960008\n```\n\n\n:::\n:::\n\n\nThe log-rank test returns a chi-square statistic of 13.1 on 1 degree of freedom (p = 0.0003) — a separation strong enough that it would survive almost any reasonable correction for multiple comparisons. The curves split apart early, within the first couple of months, and the gap holds through the rest of follow-up rather than closing back up. That shape matters: a treatment effect that's only visible in long-term survivors looks different on a KM plot than one that's there from day one, and this is the latter.\n\n## 4. Cox Proportional Hazards Model\n\nWe fit the treatment-only (unadjusted) model first, then the adjusted model, so the effect of covariate adjustment on the treatment estimate is visible rather than asserted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_unadjusted <- coxph(Surv(time, status) ~ treatment, data = trial_data)\nunadj_summary <- tidy(cox_unadjusted, exponentiate = TRUE, conf.int = TRUE)\nunadj_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term               estimate std.error statistic  p.value conf.low conf.high\n  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 treatmentTreatment    0.615     0.136     -3.58 0.000339    0.471     0.802\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_model <- coxph(Surv(time, status) ~ treatment + age + ecog, data = trial_data)\ncox_summary <- tidy(cox_model, exponentiate = TRUE, conf.int = TRUE)\ncox_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term               estimate std.error statistic     p.value conf.low conf.high\n  <chr>                 <dbl>     <dbl>     <dbl>       <dbl>    <dbl>     <dbl>\n1 treatmentTreatment    0.636   0.137       -3.30 0.000965       0.486     0.832\n2 age                   1.04    0.00778      5.07 0.000000399    1.02      1.06 \n3 ecog1                 1.92    0.149        4.35 0.0000134      1.43      2.57 \n4 ecog2                 2.66    0.200        4.91 0.000000927    1.80      3.94 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhr_unadj <- unadj_summary %>% filter(term == \"treatmentTreatment\") %>% pull(estimate)\nhr_treatment <- cox_summary %>% filter(term == \"treatmentTreatment\") %>% pull(estimate)\nhr_lower <- cox_summary %>% filter(term == \"treatmentTreatment\") %>% pull(conf.low)\nhr_upper <- cox_summary %>% filter(term == \"treatmentTreatment\") %>% pull(conf.high)\nhr_age <- cox_summary %>% filter(term == \"age\") %>% pull(estimate)\nhr_ecog1 <- cox_summary %>% filter(term == \"ecog1\") %>% pull(estimate)\nhr_ecog2 <- cox_summary %>% filter(term == \"ecog2\") %>% pull(estimate)\nhr_shift_pct <- abs(hr_treatment - hr_unadj) / hr_unadj * 100\n```\n:::\n\n\nThe unadjusted hazard ratio for treatment is 0.61. Adjusting for age and ECOG moves it to 0.64 (95% CI: 0.49–0.83) — a shift of about 3.4%, small enough to read as the kind of noise you'd expect from chance covariate imbalance under randomization rather than evidence that age or ECOG were masking the treatment effect beforehand. Treatment is the primary inferential target in this analysis: conditional on age and ECOG, treated patients are dying or progressing at 64% the rate of control patients at any given moment, which is the same thing as saying the event rate drops by 36%.\n\nAge and ECOG are in the model to adjust for baseline prognostic imbalance, not because they're the question being asked — but it's worth saying plainly that they came out as far from nuisance covariates in this fit. Each additional year of age carries a hazard ratio of 1.04, and ECOG climbs steeply: 1.92 for ECOG 1 versus ECOG 0, 2.66 for ECOG 2 versus ECOG 0, both comfortably below p = 0.0001. None of that changes how the analysis should be read — treatment is still the target, age and ECOG are still adjustment — but a model where the adjustment covariates are this strongly prognostic is also a model where skipping the adjustment would have been a real mistake, not just a formality.\n\n## 5. Proportional Hazards Assumption\n\nThe entire model rests on the assumption that the hazard ratio for each covariate is constant over time. This needs to be checked, not assumed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph_test <- cox.zph(cox_model)\nph_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           chisq df    p\ntreatment 0.3533  1 0.55\nage       0.0213  1 0.88\necog      2.8205  2 0.24\nGLOBAL    3.0654  4 0.55\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggcoxzph(ph_test)\n```\n\n::: {.cell-output-display}\n![Schoenfeld residuals for proportional hazards diagnostic](survival-analysis-final_files/figure-html/ph-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph_global_p <- ph_test$table[\"GLOBAL\", \"p\"]\nph_treatment_p <- ph_test$table[\"treatment\", \"p\"]\nph_global_p\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5469464\n```\n\n\n:::\n\n```{.r .cell-code}\nph_treatment_p\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5522347\n```\n\n\n:::\n:::\n\n\nThe global test for proportional hazards comes back at p = 0.55, and the treatment-specific test individually at p = 0.55 as well — neither close to flagging a violation. That's worth noting given the fast event accumulation described above: a disease this aggressive, with most events happening in the first few months, is exactly the kind of setting where a treatment effect sometimes front-loads (strong early, fading later) and trips the PH assumption. It doesn't happen here. The Schoenfeld residual plot for treatment sits flat across follow-up time with no visible drift, which means the hazard ratio estimated above is a reasonable single number for the whole follow-up window, not an average masking a changing effect.\n\n## 6. Functional Form Check: Martingale Residuals for Age\n\nAge enters the Cox model above as a linear term — convenient, but an assumption that needs checking rather than defaulting to. Martingale residuals from a model that excludes age, plotted against age itself with a smoothed trend line, are the standard way to see whether that linearity holds or whether the true relationship calls for a quadratic term, a spline, or categorization instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_no_age <- coxph(Surv(time, status) ~ treatment + ecog, data = trial_data)\ntrial_data$martingale_resid <- residuals(cox_no_age, type = \"martingale\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trial_data, aes(x = age, y = martingale_resid)) +\n  geom_point(alpha = 0.4, color = \"#4DBBD5\") +\n  geom_smooth(method = \"loess\", se = TRUE, color = \"#E64B35\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n  labs(x = \"Age\", y = \"Martingale residual\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Martingale residuals vs. age, with LOESS smooth, to assess linearity](survival-analysis-final_files/figure-html/martingale-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_age_quad <- coxph(Surv(time, status) ~ treatment + ecog + age + I(age^2), data = trial_data)\nage_quad_test <- anova(cox_model, cox_age_quad)\nage_quad_p <- age_quad_test$`Pr(>|Chi|)`[2]\nage_quad_p\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1797219\n```\n\n\n:::\n:::\n\n\nA likelihood ratio test comparing the linear-age model against one with an added quadratic age term gives p = 0.18 — not a small number, but well clear of anything that would suggest the linear specification is missing real curvature. The LOESS smooth in the martingale residual plot backs that up, tracking close to zero across the observed age range without a pronounced bend. Both pieces of evidence point the same way: the linear term for age in the main model is doing its job, and there's no case here for replacing it with a spline or a quadratic.\n\n## 7. Model Discrimination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc <- summary(cox_model)$concordance\nconc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        C     se(C) \n0.6555498 0.0196938 \n```\n\n\n:::\n:::\n\n\nThe model's concordance index comes out at 0.656. That's the range you'd expect from a Cox model built around one strong binary covariate plus two moderately prognostic ones (age, ECOG) — clearly above the 0.5 floor of random ranking, but nowhere near a model that reliably orders individual patients' survival times. The gap is structural, not a flaw to apologize for: concordance scores every pair of patients in the dataset, including pairs where both are control or both are treatment and age/ECOG are the only thing separating them, and those two variables only carry so much individual-level discriminative power on their own. A binary treatment indicator with a hazard ratio around 0.6 simply can't push concordance much past the mid-0.6s, no matter how cleanly the model is specified.\n\n## 8. Patient-Level Illustration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_patients <- tibble(\n  treatment = factor(c(\"Control\", \"Treatment\"), levels = c(\"Control\", \"Treatment\")),\n  age = c(62, 62),\n  ecog = factor(c(\"1\", \"1\"), levels = c(\"0\", \"1\", \"2\"))\n)\n\nsurv_fit_patients <- survfit(cox_model, newdata = new_patients)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- tibble(\n  time = rep(surv_fit_patients$time, 2),\n  surv = c(surv_fit_patients$surv[, 1], surv_fit_patients$surv[, 2]),\n  arm = rep(c(\"Control\", \"Treatment\"), each = length(surv_fit_patients$time))\n)\n\nggplot(plot_data, aes(x = time, y = surv, color = arm)) +\n  geom_step(linewidth = 1) +\n  scale_color_manual(values = c(\"#E64B35\", \"#4DBBD5\")) +\n  labs(x = \"Time (months)\", y = \"Predicted survival probability\", color = \"Arm\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Predicted survival curves for a 62-year-old, ECOG 1 patient under each treatment arm](survival-analysis-final_files/figure-html/patient-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurv_12mo_control <- surv_fit_patients$surv[which.min(abs(surv_fit_patients$time - 12)), 1]\nsurv_12mo_treatment <- surv_fit_patients$surv[which.min(abs(surv_fit_patients$time - 12)), 2]\nsurv_12mo_control\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         1 \n0.04847591 \n```\n\n\n:::\n\n```{.r .cell-code}\nsurv_12mo_treatment\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        2 \n0.1460643 \n```\n\n\n:::\n:::\n\n\nFor a 62-year-old patient with ECOG 1 — a fairly typical profile in this cohort — the model puts 12-month survival at 5% under control and 15% under treatment. Both numbers are low, which tracks with the median follow-up times from Section 2: most events in this simulated population happen well before the one-year mark, so 12 months is already deep into the tail of the survival curve for either arm. The 10-percentage-point gap is the clinically interpretable counterpart to the hazard ratio above — the HR describes a constant rate ratio, this describes what that rate ratio actually buys a specific patient by a specific point in time, and in a disease this aggressive, tripling the absolute survival probability at 12 months (even from a low base) is the kind of number a clinician would actually act on.\n\n## Takeaways\n\n- Adjusted treatment HR lands at 0.64 (95% CI 0.49–0.83) — a 36% reduction in event rate, and the headline result of this analysis. Age and ECOG sit alongside it as adjustment covariates, not co-equal findings, even though both turned out to be strongly prognostic in their own right.\n- Moving from unadjusted (0.61) to adjusted (0.64) HR shifted the treatment estimate by only 3.4%, which is what you'd expect from randomization noise rather than meaningful confounding. Showing both numbers, instead of just the final one, is what makes that distinction visible rather than asserted.\n- The PH assumption held cleanly (GLOBAL p = 0.55), notably so given this was a fast-progressing simulated disease — exactly the kind of setting where front-loaded treatment effects sometimes violate proportionality, and didn't here.\n- Concordance came in at 0.656, the expected ceiling for a model carrying one strong binary covariate and two moderately prognostic continuous/ordinal ones — not a fit problem, just what concordance does with this covariate structure.\n- A 10-percentage-point absolute survival gap at 12 months (5% vs. 15%) is the patient-facing translation of the hazard ratio above; in an aggressive disease course like this one, that gap represents tripling an already-low survival probability, which is a number worth stating plainly rather than softening.\n- Age's linear specification checked out: a quadratic term added nothing (LRT p = 0.18), and the martingale residual smooth stayed flat across the age range. Worth confirming rather than assuming, even though it ended up changing nothing about the final model.\n- Age and ECOG weren't passive adjustment terms here — both came out significant at p < 0.0001 with real magnitude (ECOG 2 vs. 0 carrying close to triple the hazard of ECOG 0). They still aren't the question being asked, but skipping their inclusion would have been a real omission, not a stylistic choice.\n\nWhat makes Cox regression durable as a method is that it separates \"does the covariate matter\" from \"what shape does the baseline hazard take.\" That separation only holds, though, if proportionality actually gets checked against the data in front of you — this one passed, but plenty don't, and you wouldn't know either way without looking.\n\n#Biostatistics #SurvivalAnalysis #CoxRegression #ClinicalTrials #Bioinformatics #RStats\n",
    "supporting": [
      "survival-analysis-final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}